export interface SeedJob {
  title: string;
  category: string;
  description: string;
  tasks: string[];
  skills: string[];
  tools: string[];
  pathway: string[];
  min_salary: number;
  avg_salary: number;
  max_salary: number;
  market_saturation: "Undersupplied" | "Balanced" | "Oversupplied";
  growth_outlook: string;
  remote_rating: "Fully Remote Friendly" | "Hybrid" | "On-site";
}

export const seedJobs: SeedJob[] = [
  // ───────────────────────────── Technology ─────────────────────────────
  {
    title: "Junior Software Engineer",
    category: "Technology",
    description:
      "Junior Software Engineers build and maintain web and mobile applications under the guidance of senior developers, writing production code, fixing bugs, and learning the Philippine tech industry's fast-moving delivery cadence. It is one of the highest-leverage entry points into tech, with a clear, well-documented promotion ladder.",
    tasks: [
      "Write and test application code from tickets and specs",
      "Fix bugs reported by QA or production monitoring",
      "Participate in code reviews and daily standups",
      "Document features and contribute to internal wikis",
    ],
    skills: ["Problem solving", "Version control (Git)", "Data structures & algorithms", "Communication"],
    tools: ["JavaScript", "React", "Node.js", "Git", "VS Code"],
    pathway: ["Junior Software Engineer", "Software Engineer II", "Senior Software Engineer", "Engineering Lead"],
    min_salary: 30000,
    avg_salary: 40000,
    max_salary: 55000,
    market_saturation: "Balanced",
    growth_outlook: "High (+22% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Data Analyst",
    category: "Technology",
    description:
      "Data Analysts turn raw business data into dashboards and recommendations for finance, marketing, and operations teams. Demand has surged as Philippine companies and outsourcing hubs invest heavily in data-driven decision-making, making this one of the fastest-growing entry points into the analytics career track.",
    tasks: [
      "Clean and transform raw datasets from multiple sources",
      "Build dashboards and recurring reports",
      "Run statistical analysis to answer business questions",
      "Present findings to non-technical stakeholders",
    ],
    skills: ["SQL", "Statistical reasoning", "Data visualization", "Business acumen"],
    tools: ["SQL", "Excel", "Power BI", "Python", "Tableau"],
    pathway: ["Data Analyst", "Senior Data Analyst", "Analytics Manager", "Head of Data & Insights"],
    min_salary: 28000,
    avg_salary: 38000,
    max_salary: 58000,
    market_saturation: "Undersupplied",
    growth_outlook: "High (+42% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Cloud & DevOps Engineer",
    category: "Technology",
    description:
      "Cloud & DevOps Engineers design and maintain the infrastructure that keeps modern applications running: deployment pipelines, container orchestration, and cloud cost efficiency. As global companies migrate infrastructure to AWS, Azure, and GCP, PH-based cloud talent has become one of the most sought-after and highest-paid technical specializations.",
    tasks: [
      "Build and maintain CI/CD pipelines",
      "Manage cloud infrastructure and container orchestration",
      "Monitor system reliability and respond to incidents",
      "Optimize cloud spend and enforce security policies",
    ],
    skills: ["Systems administration", "Automation scripting", "Networking fundamentals", "Incident response"],
    tools: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD (GitHub Actions)"],
    pathway: ["Junior DevOps Engineer", "Cloud Engineer", "Senior DevOps Engineer", "Platform / Infrastructure Lead"],
    min_salary: 45000,
    avg_salary: 70000,
    max_salary: 120000,
    market_saturation: "Undersupplied",
    growth_outlook: "High (+38% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "UI/UX Designer",
    category: "Technology",
    description:
      "UI/UX Designers research user needs and translate them into intuitive product interfaces, working closely with engineers and product managers. The Philippines has become a regional hub for design talent serving startups and enterprises across Southeast Asia, Australia, and the US, largely on a remote or hybrid basis.",
    tasks: [
      "Conduct user research and usability testing",
      "Create wireframes, prototypes, and high-fidelity UI",
      "Maintain and evolve design systems",
      "Collaborate with engineers on implementation feasibility",
    ],
    skills: ["User research", "Visual design", "Prototyping", "Cross-functional collaboration"],
    tools: ["Figma", "Adobe XD", "Miro", "Notion"],
    pathway: ["Junior UI/UX Designer", "Product Designer", "Senior Product Designer", "Design Lead"],
    min_salary: 30000,
    avg_salary: 42000,
    max_salary: 68000,
    market_saturation: "Balanced",
    growth_outlook: "High (+18% YoY)",
    remote_rating: "Fully Remote Friendly",
  },

  // ───────────────────────────── Outsourcing (BPO) ─────────────────────────────
  {
    title: "Customer Service Representative",
    category: "Outsourcing",
    description:
      "Customer Service Representatives handle inbound calls, chats, and emails for international clients across telecom, retail, and finance accounts. It remains the single largest entry point into the Philippine BPO industry, offering fast hiring, structured training, and a well-worn path into leadership roles.",
    tasks: [
      "Handle inbound customer calls, chats, and emails",
      "Resolve account, billing, and product issues",
      "Log interactions accurately in the CRM",
      "Meet quality and average-handling-time targets",
    ],
    skills: ["Verbal communication", "Active listening", "Patience under pressure", "Basic computer literacy"],
    tools: ["CRM software", "Zendesk", "Avaya / dialer systems"],
    pathway: ["Customer Service Representative", "Senior CSR / SME", "Team Leader", "Operations Manager"],
    min_salary: 18000,
    avg_salary: 23000,
    max_salary: 30000,
    market_saturation: "Oversupplied",
    growth_outlook: "Stable (+4% YoY)",
    remote_rating: "Hybrid",
  },
  {
    title: "Virtual Assistant",
    category: "Outsourcing",
    description:
      "Virtual Assistants provide remote administrative, scheduling, and support services to overseas clients, ranging from solo entrepreneurs to mid-sized agencies. It is one of the most accessible fully-remote income sources in the country, with pay scaling quickly for VAs who specialize in a niche like e-commerce or executive support.",
    tasks: [
      "Manage client calendars, inboxes, and travel bookings",
      "Handle data entry, research, and basic bookkeeping",
      "Coordinate with vendors and other team members",
      "Support social media scheduling and light content work",
    ],
    skills: ["Organization", "Written communication", "Time management", "Discretion & reliability"],
    tools: ["Google Workspace", "Trello / Asana", "Slack", "Canva"],
    pathway: ["General Virtual Assistant", "Specialized VA (e.g. e-commerce, EA)", "VA Team Lead", "Agency Owner"],
    min_salary: 25000,
    avg_salary: 45000,
    max_salary: 65000,
    market_saturation: "Balanced",
    growth_outlook: "High (+20% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Technical Support Specialist",
    category: "Outsourcing",
    description:
      "Technical Support Specialists troubleshoot hardware, software, and connectivity issues for international customers, often for telecom or SaaS accounts. It pays a premium over general customer service roles and is a common stepping stone into IT and cloud careers.",
    tasks: [
      "Diagnose and resolve technical issues via call or chat",
      "Escalate complex tickets to engineering teams",
      "Walk customers through step-by-step fixes",
      "Maintain a personal knowledge base of common issues",
    ],
    skills: ["Technical troubleshooting", "Clear communication", "Patience", "Basic networking knowledge"],
    tools: ["Remote desktop tools", "Ticketing systems (Zendesk, Jira)", "Windows/macOS/Linux basics"],
    pathway: ["Technical Support Specialist", "Senior Technical Support", "IT Support Team Lead", "Systems Administrator"],
    min_salary: 22000,
    avg_salary: 30000,
    max_salary: 42000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+9% YoY)",
    remote_rating: "Hybrid",
  },
  {
    title: "BPO Team Leader",
    category: "Outsourcing",
    description:
      "BPO Team Leaders manage a pod of 10-20 agents, owning performance coaching, schedule adherence, and client-facing metrics. It is the natural next step for high-performing agents and one of the clearest examples of internal promotion pathways in the Philippine labor market.",
    tasks: [
      "Coach agents on quality, productivity, and adherence",
      "Run daily huddles and one-on-one performance reviews",
      "Report account metrics to operations management",
      "Handle escalations from agents and clients",
    ],
    skills: ["People management", "Coaching", "Data-driven reporting", "Conflict resolution"],
    tools: ["Workforce management software", "Excel", "CRM dashboards"],
    pathway: ["Team Leader", "Operations Manager", "Site Director", "VP of Operations"],
    min_salary: 35000,
    avg_salary: 50000,
    max_salary: 72000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+8% YoY)",
    remote_rating: "On-site",
  },

  // ───────────────────────────── Healthcare ─────────────────────────────
  {
    title: "Registered Nurse",
    category: "Healthcare",
    description:
      "Registered Nurses deliver direct patient care in hospitals, clinics, and increasingly in remote patient-monitoring and health-tech roles. Local pay has historically lagged behind overseas postings, but hospital pay scales have risen sharply in recent years alongside growing demand for health information and telehealth specialists.",
    tasks: [
      "Administer medications and monitor patient vitals",
      "Coordinate care plans with physicians",
      "Document patient records accurately",
      "Educate patients and families on care instructions",
    ],
    skills: ["Clinical assessment", "Empathy", "Attention to detail", "Crisis management"],
    tools: ["Electronic Medical Records (EMR)", "Vital sign monitors", "Medication administration systems"],
    pathway: ["Staff Nurse", "Charge Nurse", "Nurse Supervisor", "Director of Nursing"],
    min_salary: 22000,
    avg_salary: 30000,
    max_salary: 48000,
    market_saturation: "Undersupplied",
    growth_outlook: "High (+15% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Medical Technologist",
    category: "Healthcare",
    description:
      "Medical Technologists run laboratory diagnostic tests that clinicians rely on for treatment decisions, working in hospital labs, diagnostic centers, and research facilities. Board licensure is required, and demand remains strong across both metro and provincial healthcare facilities.",
    tasks: [
      "Perform blood, tissue, and fluid diagnostic tests",
      "Operate and maintain laboratory equipment",
      "Verify and report test results to physicians",
      "Follow strict quality-control and safety protocols",
    ],
    skills: ["Laboratory technique", "Precision", "Regulatory compliance", "Analytical thinking"],
    tools: ["Lab analyzers", "Microscopy equipment", "Laboratory information systems"],
    pathway: ["Medical Technologist", "Senior Medical Technologist", "Laboratory Supervisor", "Laboratory Manager"],
    min_salary: 20000,
    avg_salary: 28000,
    max_salary: 40000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+10% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Physical Therapist",
    category: "Healthcare",
    description:
      "Physical Therapists design and guide rehabilitation programs for patients recovering from injury, surgery, or chronic conditions, working in hospitals, clinics, or private practice. Growing awareness of preventive and sports rehab care is expanding private-practice opportunities beyond the traditional hospital track.",
    tasks: [
      "Assess patient mobility and design treatment plans",
      "Guide patients through rehabilitation exercises",
      "Track and document patient progress",
      "Coordinate with physicians on treatment adjustments",
    ],
    skills: ["Anatomy knowledge", "Patient communication", "Manual therapy technique", "Program design"],
    tools: ["Rehabilitation equipment", "Electrotherapy devices", "Patient management software"],
    pathway: ["Physical Therapist", "Senior Physical Therapist", "Clinic Supervisor", "Private Practice Owner"],
    min_salary: 25000,
    avg_salary: 35000,
    max_salary: 55000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+11% YoY)",
    remote_rating: "On-site",
  },

  // ───────────────────────────── Engineering ─────────────────────────────
  {
    title: "Civil Engineer",
    category: "Engineering",
    description:
      "Civil Engineers plan, design, and supervise the construction of buildings, roads, and infrastructure projects. The Philippines' ongoing infrastructure push and rapid urbanization have kept demand for licensed civil engineers consistently strong across both government and private-sector projects.",
    tasks: [
      "Prepare structural designs and technical drawings",
      "Supervise construction sites for code compliance",
      "Conduct site inspections and quality checks",
      "Coordinate with architects, contractors, and regulators",
    ],
    skills: ["Structural analysis", "Project management", "Technical drafting", "Regulatory compliance"],
    tools: ["AutoCAD", "Civil 3D", "MS Project", "Surveying instruments"],
    pathway: ["Junior Civil Engineer", "Project Engineer", "Project Manager", "Principal / Construction Director"],
    min_salary: 25000,
    avg_salary: 35000,
    max_salary: 58000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+12% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Electrical Engineer",
    category: "Engineering",
    description:
      "Electrical Engineers design and maintain power distribution, wiring, and control systems for buildings, factories, and utilities. Growth in renewable energy, semiconductor manufacturing, and industrial automation has broadened career options well beyond traditional construction sites.",
    tasks: [
      "Design electrical systems and circuit layouts",
      "Ensure compliance with the Philippine Electrical Code",
      "Test and commission electrical installations",
      "Troubleshoot system faults and power quality issues",
    ],
    skills: ["Circuit design", "Code compliance", "Troubleshooting", "Technical documentation"],
    tools: ["AutoCAD Electrical", "PLC programming tools", "Power system analysis software"],
    pathway: ["Junior Electrical Engineer", "Electrical Engineer", "Senior Engineer", "Engineering Manager"],
    min_salary: 26000,
    avg_salary: 38000,
    max_salary: 62000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+13% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Mechanical Engineer",
    category: "Engineering",
    description:
      "Mechanical Engineers design, test, and maintain mechanical systems and equipment across manufacturing, energy, and industrial plants. Manufacturing recovery and factory automation investment continue to sustain demand for licensed mechanical engineers nationwide.",
    tasks: [
      "Design and evaluate mechanical systems and equipment",
      "Run stress, thermal, and reliability testing",
      "Oversee equipment installation and maintenance schedules",
      "Investigate mechanical failures and recommend fixes",
    ],
    skills: ["Mechanical design", "Root-cause analysis", "Maintenance planning", "Technical reporting"],
    tools: ["SolidWorks", "AutoCAD", "MATLAB", "CMMS software"],
    pathway: ["Junior Mechanical Engineer", "Mechanical Engineer", "Senior Engineer", "Plant / Engineering Manager"],
    min_salary: 25000,
    avg_salary: 36000,
    max_salary: 60000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+10% YoY)",
    remote_rating: "On-site",
  },

  // ───────────────────────────── Finance ─────────────────────────────
  {
    title: "Accountant",
    category: "Finance",
    description:
      "Accountants manage financial records, tax compliance, and reporting for businesses of every size, from sole proprietorships to multinational shared-service centers. CPA licensure significantly widens both pay and mobility, including into outsourced finance-and-accounting roles serving overseas clients.",
    tasks: [
      "Prepare and reconcile financial statements",
      "Ensure BIR and regulatory tax compliance",
      "Process accounts payable and receivable",
      "Support internal and external audits",
    ],
    skills: ["Financial reporting", "Tax regulations", "Attention to detail", "Analytical thinking"],
    tools: ["QuickBooks", "SAP", "Excel", "BIR eFPS"],
    pathway: ["Junior Accountant", "Senior Accountant", "Finance Manager", "Finance Director / CFO"],
    min_salary: 22000,
    avg_salary: 32000,
    max_salary: 55000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+9% YoY)",
    remote_rating: "Hybrid",
  },
  {
    title: "Financial Analyst",
    category: "Finance",
    description:
      "Financial Analysts evaluate company performance, build forecasting models, and support investment or budgeting decisions for corporates, banks, and fintech firms. The rise of Philippine fintech and digital banking has created a steady stream of analyst roles beyond traditional banking.",
    tasks: [
      "Build financial models and forecasts",
      "Analyze budget variances and cost drivers",
      "Prepare investment and performance reports",
      "Present recommendations to management",
    ],
    skills: ["Financial modeling", "Excel mastery", "Critical thinking", "Presentation skills"],
    tools: ["Excel", "Power BI", "Bloomberg Terminal", "SQL"],
    pathway: ["Junior Financial Analyst", "Financial Analyst", "Senior Analyst", "Finance Manager"],
    min_salary: 28000,
    avg_salary: 40000,
    max_salary: 68000,
    market_saturation: "Balanced",
    growth_outlook: "High (+16% YoY)",
    remote_rating: "Hybrid",
  },
  {
    title: "Bank Teller",
    category: "Finance",
    description:
      "Bank Tellers handle over-the-counter transactions, account inquiries, and basic financial product promotion at branch level. It remains a common, stable entry point into a full banking career, with structured internal paths into supervisory and relationship-management roles.",
    tasks: [
      "Process deposits, withdrawals, and payments",
      "Verify customer identity and transaction accuracy",
      "Cross-sell basic banking products",
      "Balance the cash drawer at end of shift",
    ],
    skills: ["Accuracy under pressure", "Customer service", "Cash handling", "Basic sales aptitude"],
    tools: ["Core banking systems", "Cash counting machines"],
    pathway: ["Bank Teller", "Senior Teller", "Branch Supervisor", "Branch Manager"],
    min_salary: 18000,
    avg_salary: 22000,
    max_salary: 30000,
    market_saturation: "Oversupplied",
    growth_outlook: "Stable (+3% YoY)",
    remote_rating: "On-site",
  },

  // ───────────────────────────── Marketing ─────────────────────────────
  {
    title: "Digital Marketing Specialist",
    category: "Marketing",
    description:
      "Digital Marketing Specialists plan and run paid, organic, and email campaigns to grow brand reach and sales for local and overseas clients. As Philippine SMEs and outsourced marketing teams accelerate their shift online, this has become one of the fastest-hiring roles in the marketing function.",
    tasks: [
      "Plan and execute digital ad campaigns",
      "Analyze campaign performance and optimize spend",
      "Manage email marketing and lead nurture flows",
      "Coordinate with designers and content writers",
    ],
    skills: ["Campaign strategy", "Analytics interpretation", "Copywriting", "A/B testing"],
    tools: ["Google Ads", "Meta Ads Manager", "Google Analytics", "Mailchimp"],
    pathway: ["Digital Marketing Specialist", "Senior Specialist", "Marketing Manager", "Head of Growth"],
    min_salary: 24000,
    avg_salary: 32000,
    max_salary: 50000,
    market_saturation: "Balanced",
    growth_outlook: "High (+25% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Social Media Manager / Content Creator",
    category: "Marketing",
    description:
      "Social Media Managers plan, produce, and publish content that builds brand audiences on Instagram, TikTok, and Facebook. The creator economy and brand demand for authentic content have turned this into a viable full-time career for Filipinos with strong storytelling and editing instincts.",
    tasks: [
      "Plan and produce short-form video and image content",
      "Manage posting calendars across platforms",
      "Engage with audiences and monitor brand sentiment",
      "Report on engagement and follower growth",
    ],
    skills: ["Content strategy", "Video editing basics", "Trend awareness", "Community engagement"],
    tools: ["CapCut", "Canva", "Meta Business Suite", "TikTok Creative Center"],
    pathway: ["Content Creator", "Social Media Manager", "Content Lead", "Head of Brand & Content"],
    min_salary: 22000,
    avg_salary: 30000,
    max_salary: 48000,
    market_saturation: "Oversupplied",
    growth_outlook: "High (+20% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "SEO Specialist",
    category: "Marketing",
    description:
      "SEO Specialists improve a website's organic search visibility through technical audits, content strategy, and link-building. It's a highly remote-friendly niche within marketing, with strong demand from overseas agencies looking for cost-efficient, skilled SEO talent.",
    tasks: [
      "Conduct technical SEO audits and fix issues",
      "Research keywords and plan content briefs",
      "Build and monitor backlink profiles",
      "Track rankings and organic traffic performance",
    ],
    skills: ["Keyword research", "Technical auditing", "Content planning", "Data analysis"],
    tools: ["Google Search Console", "Ahrefs / SEMrush", "Screaming Frog", "Google Analytics"],
    pathway: ["SEO Associate", "SEO Specialist", "SEO Manager", "Head of Organic Growth"],
    min_salary: 25000,
    avg_salary: 35000,
    max_salary: 55000,
    market_saturation: "Balanced",
    growth_outlook: "High (+19% YoY)",
    remote_rating: "Fully Remote Friendly",
  },

  // ───────────────────────────── Education ─────────────────────────────
  {
    title: "K-12 Teacher (Private School)",
    category: "Education",
    description:
      "Private school teachers plan lessons, manage classrooms, and assess student progress across basic education levels. Pay varies widely by school tier, with international and IB-curriculum schools offering meaningfully higher compensation than the sector average.",
    tasks: [
      "Plan and deliver lessons aligned to the curriculum",
      "Assess and record student performance",
      "Manage classroom behavior and engagement",
      "Communicate with parents on student progress",
    ],
    skills: ["Lesson planning", "Classroom management", "Subject mastery", "Patience"],
    tools: ["Learning management systems", "Google Classroom", "Presentation software"],
    pathway: ["Teacher", "Level Coordinator", "Department Head", "Academic Principal"],
    min_salary: 18000,
    avg_salary: 25000,
    max_salary: 38000,
    market_saturation: "Balanced",
    growth_outlook: "Stable (+6% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Corporate Trainer",
    category: "Education",
    description:
      "Corporate Trainers design and deliver upskilling programs for employees, ranging from onboarding to leadership development. Rapid BPO and corporate hiring has kept steady demand for trainers who can ramp new hires quickly and consistently.",
    tasks: [
      "Design training curricula and materials",
      "Facilitate in-person and virtual training sessions",
      "Measure training effectiveness and iterate",
      "Coach managers on coaching and feedback delivery",
    ],
    skills: ["Instructional design", "Public speaking", "Needs assessment", "Facilitation"],
    tools: ["LMS platforms", "PowerPoint / Canva", "Survey tools"],
    pathway: ["Training Associate", "Corporate Trainer", "Training Manager", "Head of Learning & Development"],
    min_salary: 28000,
    avg_salary: 38000,
    max_salary: 58000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+11% YoY)",
    remote_rating: "Hybrid",
  },

  // ───────────────────────────── Government ─────────────────────────────
  {
    title: "LGU Administrative Officer",
    category: "Government",
    description:
      "Administrative Officers support local government units with records management, permit processing, and constituent services. Civil-service roles offer strong job security and structured pay grades, appealing to job-seekers who value long-term stability over higher private-sector pay.",
    tasks: [
      "Process permits, licenses, and public documents",
      "Maintain accurate government records",
      "Assist constituents with inquiries and requests",
      "Support budget preparation and procurement documentation",
    ],
    skills: ["Records management", "Public service orientation", "Regulatory knowledge", "Attention to detail"],
    tools: ["Government records systems", "MS Office", "Local e-governance platforms"],
    pathway: ["Administrative Aide", "Administrative Officer", "Division Chief", "Department Head"],
    min_salary: 20000,
    avg_salary: 28000,
    max_salary: 40000,
    market_saturation: "Balanced",
    growth_outlook: "Stable (+5% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Public School Teacher (DepEd)",
    category: "Government",
    description:
      "DepEd Teachers deliver basic education in public elementary and secondary schools nationwide under a standardized government pay scale. Recent salary-grade increases and a large annual hiring intake have made this one of the most stable, if competitive, government career tracks.",
    tasks: [
      "Deliver DepEd-mandated curriculum content",
      "Assess learners and submit required reports",
      "Participate in school co-curricular activities",
      "Coordinate with parents and the local community",
    ],
    skills: ["Curriculum delivery", "Classroom management", "Licensure exam mastery (LET)", "Community engagement"],
    tools: ["DepEd LMS platforms", "Learner Information System"],
    pathway: ["Teacher I", "Teacher III", "Master Teacher", "School Principal"],
    min_salary: 27000,
    avg_salary: 30000,
    max_salary: 45000,
    market_saturation: "Oversupplied",
    growth_outlook: "Stable (+4% YoY)",
    remote_rating: "On-site",
  },

  // ───────────────────────────── Creative ─────────────────────────────
  {
    title: "Graphic Designer",
    category: "Creative",
    description:
      "Graphic Designers create visual assets for branding, marketing, and digital products across agencies, in-house teams, and freelance work. It's a highly saturated entry field, but designers who build a strong specialized portfolio (e.g. packaging, motion, or UI) command significantly higher rates.",
    tasks: [
      "Design branding, marketing, and social assets",
      "Prepare print-ready and digital-ready files",
      "Collaborate with marketing and product teams",
      "Maintain brand consistency across deliverables",
    ],
    skills: ["Visual composition", "Typography", "Brand consistency", "Client communication"],
    tools: ["Adobe Photoshop", "Illustrator", "Figma", "Canva"],
    pathway: ["Junior Graphic Designer", "Graphic Designer", "Senior / Art Director", "Creative Director"],
    min_salary: 20000,
    avg_salary: 28000,
    max_salary: 45000,
    market_saturation: "Oversupplied",
    growth_outlook: "Moderate (+9% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Video Editor",
    category: "Creative",
    description:
      "Video Editors cut and polish footage into finished content for YouTube channels, ad agencies, and social brands. Explosive demand for short-form and long-form video content has made this one of the most in-demand freelance and remote creative skills in the country.",
    tasks: [
      "Edit raw footage into polished final cuts",
      "Add motion graphics, color grading, and sound design",
      "Work from creative briefs and revision notes",
      "Manage multiple project deadlines simultaneously",
    ],
    skills: ["Storytelling through editing", "Color grading", "Sound design basics", "Time management"],
    tools: ["Adobe Premiere Pro", "After Effects", "DaVinci Resolve", "CapCut"],
    pathway: ["Junior Video Editor", "Video Editor", "Senior Editor", "Post-Production Lead"],
    min_salary: 22000,
    avg_salary: 32000,
    max_salary: 52000,
    market_saturation: "Balanced",
    growth_outlook: "High (+21% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Game Developer",
    category: "Creative",
    description:
      "Game Developers build gameplay systems, mechanics, and content for mobile, PC, and console titles. A small but growing local studio scene, combined with remote contracts from overseas publishers, has slowly built a real career track for Filipino game developers.",
    tasks: [
      "Implement gameplay mechanics and systems",
      "Optimize performance across target devices",
      "Collaborate with artists and designers on features",
      "Debug and playtest builds throughout development",
    ],
    skills: ["Programming logic", "Game design sense", "Performance optimization", "Collaboration"],
    tools: ["Unity", "Unreal Engine", "C#", "Git"],
    pathway: ["Junior Game Developer", "Game Developer", "Senior / Lead Developer", "Technical Director"],
    min_salary: 28000,
    avg_salary: 40000,
    max_salary: 68000,
    market_saturation: "Undersupplied",
    growth_outlook: "High (+17% YoY)",
    remote_rating: "Hybrid",
  },

  // ───────────────────────────── Trades ─────────────────────────────
  {
    title: "Electrician",
    category: "Trades",
    description:
      "Electricians install, inspect, and repair electrical systems in homes, buildings, and industrial facilities. It's a licensed trade with reliable local demand and a well-known route to significantly higher overseas pay for those who pursue POEA-accredited deployment.",
    tasks: [
      "Install and maintain wiring and electrical systems",
      "Diagnose and repair electrical faults",
      "Ensure work meets safety and code standards",
      "Read blueprints and electrical schematics",
    ],
    skills: ["Electrical installation", "Safety compliance", "Blueprint reading", "Troubleshooting"],
    tools: ["Multimeters", "Hand and power tools", "Conduit benders"],
    pathway: ["Apprentice Electrician", "Licensed Electrician", "Master Electrician", "Electrical Contractor / OFW Deployment"],
    min_salary: 18000,
    avg_salary: 24000,
    max_salary: 38000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+10% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "Welder",
    category: "Trades",
    description:
      "Welders fuse and fabricate metal components for construction, manufacturing, and shipbuilding projects. TESDA-certified welders are in strong demand both locally and among overseas employers, making this one of the clearest trade-to-OFW income pathways in the country.",
    tasks: [
      "Read fabrication drawings and specifications",
      "Perform welding using appropriate techniques and equipment",
      "Inspect welds for structural integrity",
      "Maintain welding equipment and safety gear",
    ],
    skills: ["Welding technique (SMAW/TIG/MIG)", "Blueprint reading", "Safety discipline", "Physical stamina"],
    tools: ["Welding machines", "Cutting torches", "Protective equipment"],
    pathway: ["Apprentice Welder", "Certified Welder", "Senior / Pipe Welder", "Welding Supervisor / OFW Deployment"],
    min_salary: 20000,
    avg_salary: 28000,
    max_salary: 48000,
    market_saturation: "Undersupplied",
    growth_outlook: "High (+14% YoY)",
    remote_rating: "On-site",
  },
  {
    title: "HVAC Technician",
    category: "Trades",
    description:
      "HVAC Technicians install and service heating, ventilation, and air-conditioning systems for residential, commercial, and industrial clients. Growth in commercial real estate and data centers has kept steady demand for certified HVAC technicians in urban centers.",
    tasks: [
      "Install and maintain HVAC systems",
      "Diagnose mechanical and electrical faults",
      "Perform preventive maintenance visits",
      "Advise clients on system upgrades and efficiency",
    ],
    skills: ["Refrigeration systems knowledge", "Electrical basics", "Diagnostic troubleshooting", "Customer service"],
    tools: ["Refrigerant gauges", "Multimeters", "Hand tools"],
    pathway: ["HVAC Helper", "HVAC Technician", "Senior Technician", "HVAC Supervisor / Contractor"],
    min_salary: 20000,
    avg_salary: 26000,
    max_salary: 40000,
    market_saturation: "Balanced",
    growth_outlook: "Moderate (+12% YoY)",
    remote_rating: "On-site",
  },

  // ───────────────────────────── Entrepreneurship ─────────────────────────────
  {
    title: "E-commerce Store Owner",
    category: "Entrepreneurship",
    description:
      "E-commerce Store Owners build and run online retail businesses on marketplaces like Shopee, Lazada, and TikTok Shop, or their own storefronts. Low barriers to entry and platform-native logistics support have made this one of the most accessible entrepreneurship paths for Filipinos, though income is highly variable and demands strong self-discipline.",
    tasks: [
      "Source or produce products and manage inventory",
      "Run online storefronts and marketplace listings",
      "Plan and execute paid and organic marketing",
      "Manage fulfillment, customer service, and cash flow",
    ],
    skills: ["Sales & negotiation", "Basic finance", "Digital marketing", "Operations management"],
    tools: ["Shopee / Lazada Seller Center", "TikTok Shop", "Canva", "Accounting spreadsheets"],
    pathway: ["Side-hustle Seller", "Registered Sole Proprietor", "Multi-channel Brand Owner", "Scaled Retail Business"],
    min_salary: 20000,
    avg_salary: 40000,
    max_salary: 100000,
    market_saturation: "Balanced",
    growth_outlook: "High (+27% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
  {
    title: "Freelance Consultant",
    category: "Entrepreneurship",
    description:
      "Freelance Consultants sell specialized expertise (finance, marketing, HR, tech) directly to clients on a project or retainer basis, without a single full-time employer. Rising trust in remote work and the growth of freelance marketplaces have made this a realistic full-time career for experienced Filipino professionals.",
    tasks: [
      "Scope and price consulting engagements",
      "Deliver client projects and advisory sessions",
      "Manage a personal pipeline of leads and referrals",
      "Handle invoicing, taxes, and business operations solo",
    ],
    skills: ["Deep subject-matter expertise", "Client relationship management", "Self-marketing", "Business operations"],
    tools: ["Upwork / freelance marketplaces", "Invoicing tools", "Video conferencing", "Project management apps"],
    pathway: ["Part-time Freelancer", "Full-time Independent Consultant", "Retainer-based Consultant", "Boutique Consultancy Owner"],
    min_salary: 25000,
    avg_salary: 45000,
    max_salary: 90000,
    market_saturation: "Balanced",
    growth_outlook: "High (+23% YoY)",
    remote_rating: "Fully Remote Friendly",
  },
];
