// Career definitions for the KnowHow PH POC seed.
// All figures (salary, demand, saturation, timelines) are illustrative
// placeholders for a proof-of-concept — see the DataSource notes.

import type {
  EducationLevel,
  EntryDifficulty,
  PathwayType,
  RatingLevel,
  SkillLevel,
} from "@prisma/client";

export interface CareerSkillDef {
  skillSlug: string;
  proficiency: SkillLevel;
  isCore: boolean;
}

export interface CareerPathwayDef {
  type: PathwayType;
  title: string;
  description: string;
  typicalDurationMonths?: number;
  isRequired: boolean;
  order: number;
}

export interface CareerCertificationDef {
  certificationSlug: string;
  isRequired: boolean;
  notes?: string;
}

export interface QuizProfileDef {
  idealTraits: Record<string, number>;
  traitWeights: Record<string, number>;
  hardConstraints: string[];
}

export interface CareerDef {
  slug: string;
  title: string;
  shortDescription: string;
  longDescription: string;
  industrySlug: string;
  categorySlug: string;
  aliases: string[];
  responsibilities: string[];
  goodFitIf: string[];
  challengingIf: string[];
  workEnvironment: string;
  workStyleSummary: string;
  educationLevel: EducationLevel;
  entryDifficulty: EntryDifficulty;
  timeToEntryMinMonths: number;
  timeToEntryMaxMonths: number;
  remoteViability: RatingLevel;
  freelanceViability: RatingLevel;
  entryLevelTitle: string;
  midLevelTitle: string;
  seniorLevelTitle: string;
  relatedCareerSlugs: string[];
  skills: CareerSkillDef[];
  workStyleTagSlugs: string[];
  pathways: CareerPathwayDef[];
  certifications: CareerCertificationDef[];
  salaryMin: number;
  salaryMax: number;
  demand: RatingLevel;
  saturation: RatingLevel;
  salaryMethodologyNote?: string;
  quizProfile: QuizProfileDef;
  seoTitle: string;
  seoDescription: string;
}

export const CAREERS: CareerDef[] = [
  // 1 ------------------------------------------------------------------
  {
    slug: "customer-service-representative",
    title: "Customer Service Representative",
    shortDescription: "Helps customers resolve issues and answer questions by phone, chat, or email.",
    longDescription:
      "Customer Service Representatives are the front line of support for companies, handling inquiries, complaints, and transactions across phone, chat, and email channels. In the Philippines this role is a major entry point into the BPO industry, offering structured training and clear advancement paths into team leadership and quality roles.",
    industrySlug: "business-operations",
    categorySlug: "customer-operations",
    aliases: ["CSR", "Call Center Agent", "Customer Support Associate", "BPO Agent"],
    responsibilities: [
      "Respond to customer inquiries via phone, chat, or email within service-level targets.",
      "Troubleshoot account, billing, or product issues and escalate complex cases appropriately.",
      "Accurately log interactions and update customer records in the CRM system.",
      "Follow scripts and quality guidelines while adapting tone to each customer.",
      "Meet individual and team targets for resolution time and customer satisfaction.",
    ],
    goodFitIf: [
      "You stay calm and patient when someone is frustrated.",
      "You enjoy talking to a wide variety of people every day.",
      "You can follow structured processes while still sounding human.",
      "You're comfortable with a metrics-driven, shift-based environment.",
    ],
    challengingIf: [
      "Repetitive conversations across a shift feel draining to you.",
      "You dislike being measured against strict call-time and quality targets.",
      "Night-shift schedules for international accounts don't suit your lifestyle.",
    ],
    workEnvironment:
      "Typically an office or hybrid/remote setup with headset-based phone or chat work, organized into shifts that often align with a client's time zone.",
    workStyleSummary: "Structured, people-facing work with clear scripts, targets, and shift schedules.",
    educationLevel: "HIGH_SCHOOL",
    entryDifficulty: "EASY",
    timeToEntryMinMonths: 0,
    timeToEntryMaxMonths: 3,
    remoteViability: "HIGH",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Customer Service Representative",
    midLevelTitle: "Senior CSR / Team Leader",
    seniorLevelTitle: "Operations Manager",
    relatedCareerSlugs: ["virtual-assistant", "logistics-coordinator", "hr-specialist"],
    skills: [
      { skillSlug: "communication", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "customer-service", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "active-listening", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "problem-solving", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "crm-software", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "time-management", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["client-facing", "team-based", "entry-level-friendly", "high-structure"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Employer onboarding & product training",
        description: "Most CSR roles start with 1-4 weeks of paid company training rather than a formal course.",
        typicalDurationMonths: 1,
        isRequired: true,
        order: 1,
      },
      {
        type: "CERTIFICATION",
        title: "Customer service & call center readiness course",
        description: "Optional short course covering communication, tools, and BPO industry basics.",
        typicalDurationMonths: 1,
        isRequired: false,
        order: 2,
      },
    ],
    certifications: [],
    salaryMin: 15000,
    salaryMax: 22000,
    demand: "HIGH",
    saturation: "HIGH",
    quizProfile: {
      idealTraits: {
        people_oriented: 80,
        communication: 85,
        collaborative: 65,
        structured: 55,
        stability_preference: 60,
        income_priority: 45,
        remote_preference: 55,
        flexibility_preference: 50,
        education_readiness: 25,
        risk_tolerance: 30,
      },
      traitWeights: { people_oriented: 1.5, communication: 1.5 },
      hardConstraints: [],
    },
    seoTitle: "Customer Service Representative Career Guide (Philippines)",
    seoDescription: "What CSRs do, entry requirements, salary range, and growth path in the PH BPO industry.",
  },

  // 2 ------------------------------------------------------------------
  {
    slug: "virtual-assistant",
    title: "Virtual Assistant",
    shortDescription: "Provides remote administrative, technical, or creative support to clients or businesses.",
    longDescription:
      "Virtual Assistants (VAs) handle a wide mix of remote support tasks — scheduling, email management, research, social media, and basic bookkeeping — for clients ranging from solo entrepreneurs to overseas small businesses. It's one of the most accessible fully-remote careers in the Philippines, with income potential that scales as VAs specialize.",
    industrySlug: "business-operations",
    categorySlug: "administrative-support",
    aliases: ["VA", "Remote Executive Assistant", "General Virtual Assistant"],
    responsibilities: [
      "Manage a client's email, calendar, and scheduling.",
      "Conduct research and prepare summaries or reports as needed.",
      "Handle basic bookkeeping, data entry, or invoicing tasks.",
      "Support social media posting, community replies, or light content work.",
      "Coordinate with other contractors or team members on the client's behalf.",
    ],
    goodFitIf: [
      "You're self-motivated and comfortable working without close supervision.",
      "You like variety and juggling several small tasks well.",
      "You're comfortable communicating async with clients in different time zones.",
      "You want to work fully remote from day one.",
    ],
    challengingIf: [
      "You need a lot of structure or in-person guidance to stay on track.",
      "Inconsistent client workloads or income in the early months would stress you out.",
      "You prefer deep focus on one skill rather than juggling many small tasks.",
    ],
    workEnvironment:
      "Fully remote, usually working from home on a laptop, communicating with clients through chat, email, and video calls.",
    workStyleSummary: "Independent, remote-first support work with a lot of task variety.",
    educationLevel: "HIGH_SCHOOL",
    entryDifficulty: "EASY",
    timeToEntryMinMonths: 0,
    timeToEntryMaxMonths: 2,
    remoteViability: "VERY_HIGH",
    freelanceViability: "VERY_HIGH",
    entryLevelTitle: "Virtual Assistant",
    midLevelTitle: "Executive / Specialist Virtual Assistant",
    seniorLevelTitle: "VA Agency Owner / Operations Lead",
    relatedCareerSlugs: ["customer-service-representative", "hr-specialist", "digital-marketing-specialist", "bookkeeper"],
    skills: [
      { skillSlug: "communication", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "office-administration", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "time-management", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "adaptability", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "crm-software", proficiency: "INTERMEDIATE", isCore: false },
      { skillSlug: "social-media-management", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "independent", "entry-level-friendly", "client-facing"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Self-paced VA foundations",
        description: "Learn core tools (calendars, email, spreadsheets, basic CRMs) through free or paid tutorials.",
        typicalDurationMonths: 1,
        isRequired: true,
        order: 1,
      },
      {
        type: "CERTIFICATION",
        title: "Virtual assistant skills certificate",
        description: "Short online course covering VA fundamentals and client communication.",
        typicalDurationMonths: 2,
        isRequired: false,
        order: 2,
      },
      {
        type: "PORTFOLIO",
        title: "Client testimonials & portfolio",
        description: "Building a track record with early clients, often starting at lower rates.",
        typicalDurationMonths: 3,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [],
    salaryMin: 15000,
    salaryMax: 25000,
    demand: "HIGH",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        independent: 80,
        remote_preference: 90,
        flexibility_preference: 80,
        communication: 70,
        digital_fluency: 65,
        entrepreneurship: 55,
        stability_preference: 30,
        detail_oriented: 55,
        people_oriented: 50,
      },
      traitWeights: { remote_preference: 2, independent: 1.5 },
      hardConstraints: [],
    },
    seoTitle: "Virtual Assistant Career Guide (Philippines)",
    seoDescription: "How to become a virtual assistant, typical tasks, remote income potential, and skills needed.",
  },

  // 3 ------------------------------------------------------------------
  {
    slug: "data-analyst",
    title: "Data Analyst",
    shortDescription: "Collects, cleans, and interprets data to help organizations make better decisions.",
    longDescription:
      "Data Analysts turn raw business data into reports, dashboards, and recommendations that guide decisions across marketing, operations, and finance teams. The role sits at the intersection of curiosity and rigor, spending time in spreadsheets, SQL queries, and visualization tools to answer specific business questions.",
    industrySlug: "technology",
    categorySlug: "data-analytics",
    aliases: ["Business Analyst", "Reporting Analyst", "Data & Insights Analyst"],
    responsibilities: [
      "Gather and clean data from multiple systems and sources.",
      "Write SQL queries to extract and aggregate data for analysis.",
      "Build dashboards and reports that track key business metrics.",
      "Identify trends, patterns, and anomalies and summarize findings for stakeholders.",
      "Recommend data-informed actions to product, marketing, or operations teams.",
    ],
    goodFitIf: [
      "You enjoy digging into numbers to find the story behind them.",
      "You're detail-oriented and double-check your own work.",
      "You like tools like Excel, SQL, or dashboards more than most people do.",
      "You can explain technical findings in plain language.",
    ],
    challengingIf: [
      "You find repetitive data cleaning tedious rather than satisfying.",
      "You prefer people-facing work over screen-and-spreadsheet-heavy days.",
      "Ambiguous, open-ended questions without a clear right answer frustrate you.",
    ],
    workEnvironment: "Primarily desk-based, computer-heavy work, often hybrid or remote, with regular stakeholder meetings.",
    workStyleSummary: "Analytical, structured work spent mostly in data tools and dashboards.",
    educationLevel: "BACHELORS",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 3,
    timeToEntryMaxMonths: 9,
    remoteViability: "HIGH",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Junior Data Analyst",
    midLevelTitle: "Data Analyst",
    seniorLevelTitle: "Senior / Lead Data Analyst",
    relatedCareerSlugs: ["software-developer", "cybersecurity-analyst", "accountant"],
    skills: [
      { skillSlug: "excel", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "sql", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "data-analysis", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "data-visualization", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "python", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "critical-thinking", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "INTERMEDIATE", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "high-structure", "deadline-driven"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS in a quantitative field",
        description: "Statistics, Mathematics, Information Technology, Economics, or similar are common backgrounds.",
        typicalDurationMonths: 48,
        isRequired: false,
        order: 1,
      },
      {
        type: "BOOTCAMP",
        title: "Data analytics bootcamp or specialization",
        description: "Intensive program covering SQL, spreadsheets, and visualization tools.",
        typicalDurationMonths: 4,
        isRequired: false,
        order: 2,
      },
      {
        type: "PORTFOLIO",
        title: "Portfolio of analysis projects",
        description: "A few public projects showing an end-to-end analysis, from raw data to recommendation.",
        typicalDurationMonths: 2,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "google-data-analytics-cert", isRequired: false }],
    salaryMin: 22000,
    salaryMax: 38000,
    demand: "HIGH",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        analytical: 85,
        quantitative: 85,
        detail_oriented: 70,
        digital_fluency: 75,
        structured: 60,
        independent: 55,
        communication: 45,
        education_readiness: 65,
        creative: 35,
      },
      traitWeights: { analytical: 1.5, quantitative: 1.5 },
      hardConstraints: [],
    },
    seoTitle: "Data Analyst Career Guide (Philippines)",
    seoDescription: "What data analysts do, required skills, salary range, and how to break into the role.",
  },

  // 4 ------------------------------------------------------------------
  {
    slug: "software-developer",
    title: "Software Developer",
    shortDescription: "Designs, builds, and maintains software applications and systems.",
    longDescription:
      "Software Developers write and maintain the code behind websites, apps, and internal business systems. It's one of the most in-demand and remote-friendly careers in the Philippines, with multiple entry paths — a computer science degree, a coding bootcamp, or self-directed learning backed by a strong portfolio.",
    industrySlug: "technology",
    categorySlug: "software-it",
    aliases: ["Web Developer", "Software Engineer", "Programmer", "Full-Stack Developer"],
    responsibilities: [
      "Write, test, and debug code for web or application features.",
      "Collaborate with designers and product managers to translate requirements into working software.",
      "Review code and participate in team code reviews.",
      "Maintain and improve existing systems, fixing bugs and technical debt.",
      "Learn and adopt new tools, frameworks, or languages as projects require.",
    ],
    goodFitIf: [
      "You enjoy solving logic puzzles and breaking problems into smaller steps.",
      "You're comfortable with continuous self-directed learning.",
      "You can focus for long stretches on detailed, technical work.",
      "You like seeing tangible things you built actually work.",
    ],
    challengingIf: [
      "You get frustrated debugging the same issue for hours.",
      "You dislike keeping up with fast-changing tools and frameworks.",
      "Long stretches of independent, heads-down work drain you.",
    ],
    workEnvironment: "Computer-based work, often remote or hybrid, with regular team check-ins and collaborative planning.",
    workStyleSummary: "Independent, analytical, tool-heavy work building and maintaining software.",
    educationLevel: "VARIES",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 4,
    timeToEntryMaxMonths: 12,
    remoteViability: "VERY_HIGH",
    freelanceViability: "HIGH",
    entryLevelTitle: "Junior Software Developer",
    midLevelTitle: "Software Developer",
    seniorLevelTitle: "Senior Software Engineer / Tech Lead",
    relatedCareerSlugs: ["data-analyst", "cybersecurity-analyst", "ux-ui-designer"],
    skills: [
      { skillSlug: "javascript", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "python", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "git-version-control", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "problem-solving", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "sql", proficiency: "INTERMEDIATE", isCore: false },
      { skillSlug: "communication", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "independent", "high-structure"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Computer Science / Information Technology",
        description: "The traditional 4-year route, offering the broadest theoretical foundation.",
        typicalDurationMonths: 48,
        isRequired: false,
        order: 1,
      },
      {
        type: "BOOTCAMP",
        title: "Full-stack coding bootcamp",
        description: "Intensive, project-based training focused on job-ready web development skills.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 2,
      },
      {
        type: "SELF_STUDY",
        title: "Self-taught via online courses",
        description: "Structured self-study through free and paid resources, paired with real projects.",
        typicalDurationMonths: 12,
        isRequired: false,
        order: 3,
      },
      {
        type: "PORTFOLIO",
        title: "GitHub portfolio & personal projects",
        description: "A public portfolio of working projects is often what actually gets junior devs hired.",
        typicalDurationMonths: 3,
        isRequired: false,
        order: 4,
      },
    ],
    certifications: [{ certificationSlug: "aws-cloud-practitioner", isRequired: false }],
    salaryMin: 25000,
    salaryMax: 45000,
    demand: "VERY_HIGH",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        analytical: 80,
        digital_fluency: 90,
        independent: 70,
        quantitative: 75,
        structured: 55,
        creative: 40,
        education_readiness: 55,
        detail_oriented: 60,
      },
      traitWeights: { digital_fluency: 2, analytical: 1.5, independent: 1.2 },
      hardConstraints: [],
    },
    seoTitle: "Software Developer Career Guide (Philippines)",
    seoDescription: "Entry paths, in-demand skills, salary range, and remote work outlook for software developers.",
  },

  // 5 ------------------------------------------------------------------
  {
    slug: "digital-marketing-specialist",
    title: "Digital Marketing Specialist",
    shortDescription: "Plans and runs online campaigns to grow a brand's reach, engagement, and sales.",
    longDescription:
      "Digital Marketing Specialists manage a brand's presence across search, social, and email channels, combining creative content with performance data to grow an audience and drive results. The role blends creative instincts with comfort in analytics dashboards, and is one of the more accessible remote-friendly careers to break into.",
    industrySlug: "creative-media",
    categorySlug: "writing-content",
    aliases: ["Digital Marketer", "Marketing Associate", "Social Media & Marketing Specialist"],
    responsibilities: [
      "Plan and execute campaigns across social media, email, and search channels.",
      "Create or coordinate content calendars and marketing assets.",
      "Track campaign performance and adjust strategy based on data.",
      "Manage paid ad budgets and optimize for cost-effective results.",
      "Collaborate with designers, writers, and sales teams on campaign goals.",
    ],
    goodFitIf: [
      "You enjoy a mix of creative work and performance data.",
      "You like experimenting and iterating based on what the numbers show.",
      "You're comfortable juggling several campaigns and deadlines at once.",
      "You keep up with trends across social platforms naturally.",
    ],
    challengingIf: [
      "You dislike constantly shifting platform algorithms and trends.",
      "Data-driven decision-making feels tedious rather than interesting.",
      "You prefer one deep focus area over managing many channels at once.",
    ],
    workEnvironment: "Hybrid or remote, computer-based work with regular collaboration across creative and sales teams.",
    workStyleSummary: "Fast-paced, creative-meets-analytical work across multiple channels and campaigns.",
    educationLevel: "VARIES",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 1,
    timeToEntryMaxMonths: 6,
    remoteViability: "HIGH",
    freelanceViability: "HIGH",
    entryLevelTitle: "Digital Marketing Associate",
    midLevelTitle: "Digital Marketing Specialist",
    seniorLevelTitle: "Digital Marketing Manager",
    relatedCareerSlugs: ["copywriter", "e-commerce-manager", "graphic-designer"],
    skills: [
      { skillSlug: "seo", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "content-writing", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "social-media-management", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "data-analysis", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "communication", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "creativity", proficiency: "INTERMEDIATE", isCore: true },
    ],
    workStyleTagSlugs: ["remote-friendly", "deadline-driven", "creative-freedom", "client-facing"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Digital marketing foundations",
        description: "Free and paid courses from Google, HubSpot, and Meta covering core channels.",
        typicalDurationMonths: 3,
        isRequired: true,
        order: 1,
      },
      {
        type: "CERTIFICATION",
        title: "Platform certification",
        description: "Google Ads, Meta Blueprint, or HubSpot certification.",
        typicalDurationMonths: 2,
        isRequired: false,
        order: 2,
      },
      {
        type: "PORTFOLIO",
        title: "Campaign case studies",
        description: "A portfolio of campaign results, even from small or personal projects.",
        typicalDurationMonths: 2,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "hubspot-content-marketing-cert", isRequired: false }],
    salaryMin: 18000,
    salaryMax: 30000,
    demand: "HIGH",
    saturation: "HIGH",
    quizProfile: {
      idealTraits: {
        creative: 70,
        communication: 75,
        digital_fluency: 70,
        analytical: 55,
        flexibility_preference: 60,
        entrepreneurship: 45,
        people_oriented: 55,
        remote_preference: 55,
      },
      traitWeights: { communication: 1.5, creative: 1.3 },
      hardConstraints: [],
    },
    seoTitle: "Digital Marketing Specialist Career Guide (Philippines)",
    seoDescription: "Skills, entry paths, and salary expectations for digital marketing careers in the Philippines.",
  },

  // 6 ------------------------------------------------------------------
  {
    slug: "nurse",
    title: "Nurse",
    shortDescription: "Provides direct patient care in hospitals, clinics, and community health settings.",
    longDescription:
      "Registered Nurses assess, treat, and monitor patients, working closely with doctors and other healthcare staff to deliver care. In the Philippines, nursing requires a four-year degree and a licensure exam, and remains one of the most in-demand professions both locally and for overseas deployment.",
    industrySlug: "healthcare",
    categorySlug: "clinical-care",
    aliases: ["Registered Nurse", "RN", "Staff Nurse"],
    responsibilities: [
      "Assess patient conditions and monitor vital signs.",
      "Administer medications and treatments as prescribed by physicians.",
      "Maintain accurate clinical documentation and patient records.",
      "Educate patients and families on care plans and recovery.",
      "Coordinate with doctors and allied health staff on patient care plans.",
    ],
    goodFitIf: [
      "You want a career centered on directly caring for people.",
      "You stay composed and clear-headed in high-pressure situations.",
      "You're detail-oriented, especially about medication and dosage accuracy.",
      "You're willing to commit to a licensure exam after your degree.",
    ],
    challengingIf: [
      "You need a fully remote or desk-based career.",
      "Long shifts, including nights and weekends, would be hard for you to sustain.",
      "Emotionally difficult situations involving illness and loss are hard for you to process at work.",
    ],
    workEnvironment: "Hospitals, clinics, or community health settings; physically demanding, shift-based, on-site work.",
    workStyleSummary: "Hands-on, high-stakes patient care requiring composure and precision.",
    educationLevel: "LICENSE_REQUIRED",
    entryDifficulty: "HARD",
    timeToEntryMinMonths: 48,
    timeToEntryMaxMonths: 54,
    remoteViability: "VERY_LOW",
    freelanceViability: "LOW",
    entryLevelTitle: "Staff Nurse",
    midLevelTitle: "Charge Nurse / Clinical Nurse Specialist",
    seniorLevelTitle: "Nurse Supervisor / Nurse Manager",
    relatedCareerSlugs: ["medical-technologist", "k-12-teacher"],
    skills: [
      { skillSlug: "patient-care-procedures", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "clinical-documentation", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "empathy", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "critical-thinking", proficiency: "INTERMEDIATE", isCore: true },
    ],
    workStyleTagSlugs: ["team-based", "high-structure", "licensed-profession", "physically-active"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Nursing (BSN)",
        description: "A four-year nursing degree covering clinical theory and hospital practicum rotations.",
        typicalDurationMonths: 48,
        isRequired: true,
        order: 1,
      },
      {
        type: "LICENSURE",
        title: "Nurse Licensure Examination (PRC)",
        description: "Required national board exam to practice as a registered nurse.",
        typicalDurationMonths: 6,
        isRequired: true,
        order: 2,
      },
      {
        type: "APPRENTICESHIP",
        title: "Hospital clinical internship / residency",
        description: "Supervised hands-on clinical rotations, often required during and after the degree.",
        typicalDurationMonths: 12,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [
      { certificationSlug: "ph-nursing-licensure-exam", isRequired: true, notes: "Required to practice as an RN in the Philippines." },
    ],
    salaryMin: 18000,
    salaryMax: 28000,
    demand: "VERY_HIGH",
    saturation: "HIGH",
    salaryMethodologyNote:
      "Illustrative POC estimate for entry-to-mid level local hospital/clinic roles; overseas deployment pay is substantially higher and out of scope for this placeholder figure.",
    quizProfile: {
      idealTraits: {
        people_oriented: 75,
        communication: 70,
        detail_oriented: 75,
        structured: 65,
        stability_preference: 60,
        certification_readiness: 80,
        education_readiness: 80,
        hands_on: 40,
      },
      traitWeights: { certification_readiness: 1.5, education_readiness: 1.3, people_oriented: 1.2 },
      hardConstraints: ["no_licensure"],
    },
    seoTitle: "Nurse Career Guide (Philippines)",
    seoDescription: "Education path, licensure exam, salary range, and what daily nursing work is really like.",
  },

  // 7 ------------------------------------------------------------------
  {
    slug: "medical-technologist",
    title: "Medical Technologist",
    shortDescription: "Runs laboratory tests on patient samples that support diagnosis and treatment decisions.",
    longDescription:
      "Medical Technologists (also called Medical Laboratory Scientists) perform and interpret laboratory tests — blood work, cultures, and other diagnostics — that doctors rely on to diagnose and treat patients. The role requires precision and a strong science background, along with a licensure exam after a four-year degree.",
    industrySlug: "healthcare",
    categorySlug: "diagnostics",
    aliases: ["Medical Laboratory Scientist", "MedTech", "Clinical Laboratory Scientist"],
    responsibilities: [
      "Collect and prepare patient specimens for laboratory testing.",
      "Operate and maintain laboratory equipment and testing instruments.",
      "Perform tests accurately and record results following strict protocols.",
      "Verify and cross-check results before releasing them to physicians.",
      "Maintain lab safety, calibration, and quality-control standards.",
    ],
    goodFitIf: [
      "You're meticulous and rarely miss small details.",
      "You enjoy science and lab-based technical work.",
      "You can follow strict protocols precisely, every time.",
      "You're comfortable committing to a licensure exam.",
    ],
    challengingIf: [
      "You need a highly social, people-facing role day to day.",
      "You want a fully remote career.",
      "Repetitive, procedure-heavy lab work would bore you quickly.",
    ],
    workEnvironment: "Hospital or diagnostic laboratory, on-site, working with lab equipment and biological samples.",
    workStyleSummary: "Precise, procedure-driven laboratory work with minimal direct patient interaction.",
    educationLevel: "LICENSE_REQUIRED",
    entryDifficulty: "HARD",
    timeToEntryMinMonths: 48,
    timeToEntryMaxMonths: 54,
    remoteViability: "VERY_LOW",
    freelanceViability: "VERY_LOW",
    entryLevelTitle: "Medical Technologist",
    midLevelTitle: "Senior Medical Technologist",
    seniorLevelTitle: "Laboratory Supervisor / Lab Manager",
    relatedCareerSlugs: ["nurse", "data-analyst", "accountant"],
    skills: [
      { skillSlug: "medical-lab-procedures", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "clinical-documentation", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "critical-thinking", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "data-analysis", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["high-structure", "licensed-profession", "team-based"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Medical Technology / Medical Laboratory Science",
        description: "A four-year degree combining biology, chemistry, and clinical laboratory training.",
        typicalDurationMonths: 48,
        isRequired: true,
        order: 1,
      },
      {
        type: "LICENSURE",
        title: "Medical Technologist Licensure Examination (PRC)",
        description: "Required national board exam to practice as a licensed medical technologist.",
        typicalDurationMonths: 6,
        isRequired: true,
        order: 2,
      },
      {
        type: "APPRENTICESHIP",
        title: "Clinical laboratory internship",
        description: "Supervised laboratory practicum, typically completed during the degree program.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [
      { certificationSlug: "medtech-licensure", isRequired: true, notes: "Required to practice as a medical technologist." },
    ],
    salaryMin: 18000,
    salaryMax: 26000,
    demand: "MODERATE",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        detail_oriented: 85,
        analytical: 70,
        quantitative: 65,
        structured: 70,
        certification_readiness: 80,
        education_readiness: 80,
        people_oriented: 35,
        stability_preference: 60,
        independent: 45,
      },
      traitWeights: { detail_oriented: 1.5, certification_readiness: 1.4, education_readiness: 1.2 },
      hardConstraints: ["no_licensure"],
    },
    seoTitle: "Medical Technologist Career Guide (Philippines)",
    seoDescription: "Education, licensure, salary, and daily work of a medical technologist in the Philippines.",
  },

  // 8 ------------------------------------------------------------------
  {
    slug: "graphic-designer",
    title: "Graphic Designer",
    shortDescription: "Creates visual content — branding, layouts, and digital graphics — for print and digital media.",
    longDescription:
      "Graphic Designers turn ideas into visuals — logos, social media graphics, marketing materials, and layouts — that communicate a brand's message clearly and attractively. The field rewards a strong portfolio over formal credentials, making it accessible through design courses, self-study, or a design degree.",
    industrySlug: "creative-media",
    categorySlug: "design",
    aliases: ["Visual Designer", "Brand Designer", "Layout Artist"],
    responsibilities: [
      "Design graphics, layouts, and visual assets for print and digital use.",
      "Translate briefs and brand guidelines into finished visual work.",
      "Collaborate with marketing or product teams on visual direction.",
      "Prepare final files for print production or digital publishing.",
      "Maintain a consistent visual style across a brand's materials.",
    ],
    goodFitIf: [
      "You think visually and enjoy experimenting with layout and color.",
      "You take feedback on your creative work well.",
      "You're comfortable with design software and picking up new tools.",
      "You like having creative latitude in how you approach a brief.",
    ],
    challengingIf: [
      "You dislike revising work repeatedly based on client feedback.",
      "Tight, frequent deadlines feel stressful to you.",
      "You'd rather follow a fixed process than make creative judgment calls.",
    ],
    workEnvironment: "Studio, agency, in-house, or freelance; computer-based work often done remotely or hybrid.",
    workStyleSummary: "Creative, visually driven work balanced with client briefs and deadlines.",
    educationLevel: "VARIES",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 3,
    timeToEntryMaxMonths: 9,
    remoteViability: "HIGH",
    freelanceViability: "VERY_HIGH",
    entryLevelTitle: "Junior Graphic Designer",
    midLevelTitle: "Graphic Designer",
    seniorLevelTitle: "Senior / Art Director",
    relatedCareerSlugs: ["ux-ui-designer", "copywriter", "digital-marketing-specialist"],
    skills: [
      { skillSlug: "adobe-creative-suite", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "figma", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "creativity", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "creative-freedom", "client-facing", "deadline-driven"],
    pathways: [
      {
        type: "DEGREE",
        title: "BFA / BS in Multimedia Arts or Design",
        description: "A formal design degree covering design theory, typography, and production.",
        typicalDurationMonths: 48,
        isRequired: false,
        order: 1,
      },
      {
        type: "SELF_STUDY",
        title: "Self-taught via online design courses",
        description: "Learning design software and principles through structured online courses.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 2,
      },
      {
        type: "PORTFOLIO",
        title: "Design portfolio",
        description: "A strong portfolio is typically what gets designers hired, more than formal credentials.",
        typicalDurationMonths: 3,
        isRequired: true,
        order: 3,
      },
    ],
    certifications: [],
    salaryMin: 16000,
    salaryMax: 26000,
    demand: "MODERATE",
    saturation: "HIGH",
    quizProfile: {
      idealTraits: {
        creative: 85,
        digital_fluency: 65,
        detail_oriented: 55,
        independent: 60,
        communication: 45,
        flexibility_preference: 55,
        people_oriented: 40,
        entrepreneurship: 40,
      },
      traitWeights: { creative: 1.7, digital_fluency: 1.2 },
      hardConstraints: [],
    },
    seoTitle: "Graphic Designer Career Guide (Philippines)",
    seoDescription: "Skills, portfolio tips, entry paths, and salary range for graphic designers in the Philippines.",
  },

  // 9 ------------------------------------------------------------------
  {
    slug: "accountant",
    title: "Accountant",
    shortDescription: "Prepares, analyzes, and safeguards financial records for businesses or clients.",
    longDescription:
      "Accountants prepare financial statements, ensure regulatory compliance, and advise on financial decisions for businesses, government, or individual clients. Becoming a Certified Public Accountant in the Philippines requires a five-year accountancy degree and passing the CPA board exam, opening doors to audit, tax, and corporate finance roles.",
    industrySlug: "finance",
    categorySlug: "accounting",
    aliases: ["CPA", "Financial Accountant", "General Accountant"],
    responsibilities: [
      "Prepare and review financial statements and reports.",
      "Reconcile accounts and ensure accuracy of financial records.",
      "Ensure compliance with tax regulations and filing deadlines.",
      "Support budgeting, forecasting, and financial analysis.",
      "Coordinate with auditors during financial reviews.",
    ],
    goodFitIf: [
      "You're precise and comfortable working with numbers all day.",
      "You like following clear rules and standards.",
      "You're willing to commit to a licensure exam after a five-year degree.",
      "You prefer stable, structured career progression.",
    ],
    challengingIf: [
      "You need a fully remote-only role from the start.",
      "You dislike detail-heavy, compliance-driven work.",
      "A long, structured academic and licensure path doesn't appeal to you.",
    ],
    workEnvironment: "Office-based, often hybrid; heavier workload during tax season or audit periods.",
    workStyleSummary: "Structured, detail-heavy work grounded in financial rules and standards.",
    educationLevel: "LICENSE_REQUIRED",
    entryDifficulty: "HARD",
    timeToEntryMinMonths: 54,
    timeToEntryMaxMonths: 66,
    remoteViability: "MODERATE",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Junior Accountant",
    midLevelTitle: "Accountant / CPA",
    seniorLevelTitle: "Finance Manager / Controller",
    relatedCareerSlugs: ["bookkeeper", "data-analyst", "medical-technologist"],
    skills: [
      { skillSlug: "accounting-software", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "financial-reporting", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "excel", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "critical-thinking", proficiency: "INTERMEDIATE", isCore: true },
    ],
    workStyleTagSlugs: ["high-structure", "deadline-driven", "team-based", "licensed-profession"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Accountancy (BSA)",
        description: "A five-year accounting degree required before sitting the CPA board exam.",
        typicalDurationMonths: 60,
        isRequired: true,
        order: 1,
      },
      {
        type: "LICENSURE",
        title: "CPA Licensure Examination (PRC)",
        description: "Required national board exam to practice as a Certified Public Accountant.",
        typicalDurationMonths: 6,
        isRequired: true,
        order: 2,
      },
      {
        type: "CERTIFICATION",
        title: "Continuing professional development",
        description: "Ongoing CPD units required to maintain an active CPA license.",
        typicalDurationMonths: 12,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [
      { certificationSlug: "cpa-licensure", isRequired: true, notes: "Required to use the CPA title and sign audited statements." },
    ],
    salaryMin: 20000,
    salaryMax: 32000,
    demand: "HIGH",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        quantitative: 80,
        detail_oriented: 80,
        structured: 75,
        certification_readiness: 80,
        education_readiness: 80,
        stability_preference: 65,
        analytical: 65,
        independent: 45,
      },
      traitWeights: { quantitative: 1.5, detail_oriented: 1.4, certification_readiness: 1.3 },
      hardConstraints: ["no_licensure"],
    },
    seoTitle: "Accountant / CPA Career Guide (Philippines)",
    seoDescription: "The path to becoming a CPA in the Philippines, required skills, and typical salary range.",
  },

  // 10 -----------------------------------------------------------------
  {
    slug: "civil-engineer",
    title: "Civil Engineer",
    shortDescription: "Designs, plans, and oversees construction of infrastructure like roads, bridges, and buildings.",
    longDescription:
      "Civil Engineers plan and oversee the design and construction of infrastructure — buildings, roads, bridges, and water systems — ensuring projects are safe, structurally sound, and compliant with codes. The role requires a five-year engineering degree and a licensure exam, with much of the work split between design office and construction sites.",
    industrySlug: "engineering-built-environment",
    categorySlug: "civil-construction",
    aliases: ["Structural Engineer", "Construction Engineer", "Site Civil Engineer"],
    responsibilities: [
      "Design structural plans and specifications for construction projects.",
      "Perform structural analysis and ensure code compliance.",
      "Conduct site inspections and monitor construction progress.",
      "Coordinate with architects, contractors, and government permitting offices.",
      "Prepare technical documentation and project reports.",
    ],
    goodFitIf: [
      "You enjoy applying math and physics to real physical structures.",
      "You're comfortable splitting time between office design work and site visits.",
      "You're detail-oriented about safety and structural precision.",
      "You're willing to commit to a licensure exam after a five-year degree.",
    ],
    challengingIf: [
      "You need a fully remote career.",
      "You dislike site visits, fieldwork, or physically demanding environments.",
      "A long, structured academic and licensure path doesn't appeal to you.",
    ],
    workEnvironment: "Split between an office (design, planning) and active construction sites (inspection, supervision).",
    workStyleSummary: "Technical, structured work combining design precision with on-site oversight.",
    educationLevel: "LICENSE_REQUIRED",
    entryDifficulty: "HARD",
    timeToEntryMinMonths: 54,
    timeToEntryMaxMonths: 66,
    remoteViability: "VERY_LOW",
    freelanceViability: "LOW",
    entryLevelTitle: "Junior Civil Engineer",
    midLevelTitle: "Civil Engineer",
    seniorLevelTitle: "Project Engineer / Engineering Manager",
    relatedCareerSlugs: ["welder", "logistics-coordinator", "data-analyst"],
    skills: [
      { skillSlug: "cad-software", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "structural-analysis", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "problem-solving", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "blueprint-reading", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["field-work", "high-structure", "licensed-profession", "physically-active"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Civil Engineering",
        description: "A five-year engineering degree covering structural, geotechnical, and construction fundamentals.",
        typicalDurationMonths: 60,
        isRequired: true,
        order: 1,
      },
      {
        type: "LICENSURE",
        title: "Civil Engineering Licensure Examination (PRC)",
        description: "Required national board exam to practice and sign as a professional civil engineer.",
        typicalDurationMonths: 6,
        isRequired: true,
        order: 2,
      },
      {
        type: "APPRENTICESHIP",
        title: "Supervised site engineering internship",
        description: "On-the-job training under a licensed engineer, often completed during or after the degree.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [
      { certificationSlug: "civil-engineer-licensure", isRequired: true, notes: "Required to practice and seal engineering documents." },
    ],
    salaryMin: 22000,
    salaryMax: 35000,
    demand: "HIGH",
    saturation: "LOW",
    quizProfile: {
      idealTraits: {
        quantitative: 75,
        structured: 70,
        hands_on: 55,
        detail_oriented: 65,
        certification_readiness: 80,
        education_readiness: 85,
        remote_preference: 10,
        analytical: 70,
        leadership: 50,
      },
      traitWeights: { education_readiness: 1.4, certification_readiness: 1.3, quantitative: 1.2 },
      hardConstraints: ["no_licensure", "remote_only"],
    },
    seoTitle: "Civil Engineer Career Guide (Philippines)",
    seoDescription: "Degree path, licensure exam, salary range, and daily work of a civil engineer.",
  },

  // 11 -----------------------------------------------------------------
  {
    slug: "k-12-teacher",
    title: "K–12 Teacher",
    shortDescription: "Plans and delivers lessons that guide students' academic and personal development.",
    longDescription:
      "K-12 Teachers plan lessons, deliver instruction, and support the academic and social development of students in basic education. Teaching in the Philippines requires an education degree and passing the Licensure Examination for Teachers (LET), and offers a stable, structured career path centered on working closely with students and families.",
    industrySlug: "education",
    categorySlug: "teaching",
    aliases: ["Classroom Teacher", "Elementary Teacher", "Secondary Teacher"],
    responsibilities: [
      "Plan lessons aligned with curriculum standards.",
      "Deliver instruction and manage classroom activities.",
      "Assess student progress and provide feedback.",
      "Communicate with parents about student development.",
      "Maintain a safe, structured, and engaging classroom environment.",
    ],
    goodFitIf: [
      "You enjoy explaining ideas and helping others understand them.",
      "You're patient with repeated questions and varying learning paces.",
      "You're comfortable with structure, routines, and curriculum requirements.",
      "You're willing to commit to a licensure exam after your education degree.",
    ],
    challengingIf: [
      "You want a fully remote or highly flexible-schedule career.",
      "Large class sizes and administrative workload would frustrate you.",
      "You'd rather avoid a long, structured academic and licensure path.",
    ],
    workEnvironment: "In-person classroom setting, structured school-day schedule with lesson planning outside class hours.",
    workStyleSummary: "People-centered, structured work built around lesson delivery and student development.",
    educationLevel: "LICENSE_REQUIRED",
    entryDifficulty: "HARD",
    timeToEntryMinMonths: 48,
    timeToEntryMaxMonths: 54,
    remoteViability: "LOW",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Teacher I",
    midLevelTitle: "Teacher II / Master Teacher",
    seniorLevelTitle: "Head Teacher / School Principal",
    relatedCareerSlugs: ["hr-specialist", "nurse"],
    skills: [
      { skillSlug: "lesson-planning", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "classroom-management", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "communication", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "empathy", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "creativity", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["team-based", "high-structure", "licensed-profession", "client-facing"],
    pathways: [
      {
        type: "DEGREE",
        title: "Bachelor of Elementary / Secondary Education",
        description: "A four-year education degree covering pedagogy and subject-matter content.",
        typicalDurationMonths: 48,
        isRequired: true,
        order: 1,
      },
      {
        type: "LICENSURE",
        title: "Licensure Examination for Teachers (LET)",
        description: "Required national board exam to teach in Philippine public and most private schools.",
        typicalDurationMonths: 6,
        isRequired: true,
        order: 2,
      },
      {
        type: "APPRENTICESHIP",
        title: "Supervised teaching practicum",
        description: "Classroom teaching practice completed as part of the education degree.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [
      { certificationSlug: "teacher-licensure-exam", isRequired: true, notes: "Required to teach in most Philippine schools." },
    ],
    salaryMin: 20000,
    salaryMax: 27000,
    demand: "MODERATE",
    saturation: "HIGH",
    quizProfile: {
      idealTraits: {
        people_oriented: 80,
        communication: 80,
        structured: 65,
        leadership: 55,
        certification_readiness: 75,
        education_readiness: 85,
        stability_preference: 65,
        creative: 45,
        collaborative: 55,
      },
      traitWeights: { communication: 1.4, people_oriented: 1.3, education_readiness: 1.3 },
      hardConstraints: ["no_licensure", "no_further_study"],
    },
    seoTitle: "K-12 Teacher Career Guide (Philippines)",
    seoDescription: "Education path, LET licensure exam, salary range, and what teaching is really like day to day.",
  },

  // 12 -----------------------------------------------------------------
  {
    slug: "e-commerce-manager",
    title: "E-commerce Manager",
    shortDescription: "Runs and grows an online store or marketplace presence, from listings to fulfillment.",
    longDescription:
      "E-commerce Managers oversee an online store's day-to-day operations — product listings, pricing, promotions, inventory, and fulfillment — while working to grow sales across marketplaces and a brand's own site. The role suits people who like owning a business function end-to-end and are comfortable with both data and hands-on operations.",
    industrySlug: "commerce",
    categorySlug: "e-commerce",
    aliases: ["Online Store Manager", "Marketplace Manager", "E-commerce Operations Lead"],
    responsibilities: [
      "Manage product listings, pricing, and promotions across online channels.",
      "Monitor inventory levels and coordinate with suppliers or fulfillment partners.",
      "Analyze sales data to identify growth opportunities.",
      "Run or coordinate marketing campaigns to drive store traffic and conversions.",
      "Handle escalated customer issues related to orders or products.",
    ],
    goodFitIf: [
      "You like owning a business function end-to-end.",
      "You're comfortable switching between data analysis and hands-on operations.",
      "You enjoy testing ideas and quickly seeing results in sales data.",
      "You want a flexible, remote-friendly career with growth potential.",
    ],
    challengingIf: [
      "You dislike juggling many small operational details at once.",
      "Fluctuating sales and demand cycles would stress you out.",
      "You prefer a single, narrow specialization over broad ownership.",
    ],
    workEnvironment: "Remote or hybrid, computer-based work with occasional coordination with warehouses or suppliers.",
    workStyleSummary: "Operationally hands-on, data-informed work running an online storefront.",
    educationLevel: "VARIES",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 3,
    timeToEntryMaxMonths: 9,
    remoteViability: "HIGH",
    freelanceViability: "HIGH",
    entryLevelTitle: "E-commerce Associate",
    midLevelTitle: "E-commerce Manager",
    seniorLevelTitle: "Head of E-commerce / D2C Lead",
    relatedCareerSlugs: ["digital-marketing-specialist", "logistics-coordinator", "startup-founder"],
    skills: [
      { skillSlug: "inventory-management-systems", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "data-analysis", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "social-media-management", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "negotiation", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "communication", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "crm-software", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "entrepreneurial", "deadline-driven", "independent"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Online e-commerce & digital marketing courses",
        description: "Self-paced courses covering marketplace operations and digital marketing basics.",
        typicalDurationMonths: 3,
        isRequired: true,
        order: 1,
      },
      {
        type: "CERTIFICATION",
        title: "Platform seller certifications",
        description: "Shopee, Lazada, or Shopify seller programs and certifications.",
        typicalDurationMonths: 1,
        isRequired: false,
        order: 2,
      },
      {
        type: "PORTFOLIO",
        title: "Store management track record",
        description: "Hands-on experience running or growing a store, even a small personal one.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [],
    salaryMin: 20000,
    salaryMax: 32000,
    demand: "HIGH",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        entrepreneurship: 65,
        digital_fluency: 70,
        analytical: 55,
        communication: 55,
        flexibility_preference: 65,
        risk_tolerance: 55,
        independent: 60,
        detail_oriented: 50,
      },
      traitWeights: { entrepreneurship: 1.3, digital_fluency: 1.2 },
      hardConstraints: [],
    },
    seoTitle: "E-commerce Manager Career Guide (Philippines)",
    seoDescription: "What e-commerce managers do, entry paths, required skills, and salary range.",
  },

  // 13 -----------------------------------------------------------------
  {
    slug: "copywriter",
    title: "Copywriter",
    shortDescription: "Writes persuasive, clear copy for ads, websites, and marketing campaigns.",
    longDescription:
      "Copywriters write the words that sell — ad copy, website content, email campaigns, and social captions — shaping how a brand sounds and persuading audiences to act. It's a highly portfolio-driven, remote-friendly career where strong writing samples matter more than formal credentials.",
    industrySlug: "creative-media",
    categorySlug: "writing-content",
    aliases: ["Content Writer", "Marketing Copywriter", "Ad Copywriter"],
    responsibilities: [
      "Write copy for ads, websites, emails, and social media.",
      "Adapt tone and style to match different brand voices.",
      "Research products, audiences, and competitors before writing.",
      "Revise copy based on feedback and performance data.",
      "Collaborate with designers and marketers on campaign messaging.",
    ],
    goodFitIf: [
      "You enjoy playing with words and finding the right phrasing.",
      "You can adapt your writing voice to different brands and audiences.",
      "You take editorial feedback well and revise without frustration.",
      "You want an independent, remote-friendly, portfolio-driven career.",
    ],
    challengingIf: [
      "Writer's block under tight deadlines would stress you out.",
      "You dislike writing to strict briefs or brand guidelines.",
      "You'd rather work on one long project than many short pieces.",
    ],
    workEnvironment: "Remote or hybrid, mostly independent computer-based writing work with periodic feedback cycles.",
    workStyleSummary: "Independent, deadline-driven writing work guided by briefs and brand voice.",
    educationLevel: "VARIES",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 1,
    timeToEntryMaxMonths: 6,
    remoteViability: "VERY_HIGH",
    freelanceViability: "VERY_HIGH",
    entryLevelTitle: "Junior Copywriter",
    midLevelTitle: "Copywriter",
    seniorLevelTitle: "Senior Copywriter / Content Lead",
    relatedCareerSlugs: ["digital-marketing-specialist", "graphic-designer", "virtual-assistant"],
    skills: [
      { skillSlug: "content-writing", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "creativity", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "communication", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "seo", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "attention-to-detail", proficiency: "INTERMEDIATE", isCore: true },
    ],
    workStyleTagSlugs: ["remote-friendly", "creative-freedom", "independent", "deadline-driven"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Writing practice & copywriting courses",
        description: "Deliberate writing practice paired with free or paid copywriting courses.",
        typicalDurationMonths: 2,
        isRequired: true,
        order: 1,
      },
      {
        type: "PORTFOLIO",
        title: "Writing samples / portfolio site",
        description: "A small collection of spec or client work showing range and voice.",
        typicalDurationMonths: 2,
        isRequired: true,
        order: 2,
      },
      {
        type: "CERTIFICATION",
        title: "Content marketing certification",
        description: "Optional certification to strengthen a portfolio or resume.",
        typicalDurationMonths: 1,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [],
    salaryMin: 16000,
    salaryMax: 26000,
    demand: "MODERATE",
    saturation: "HIGH",
    quizProfile: {
      idealTraits: {
        creative: 80,
        communication: 75,
        independent: 65,
        flexibility_preference: 60,
        digital_fluency: 45,
        detail_oriented: 55,
        analytical: 45,
        remote_preference: 60,
      },
      traitWeights: { creative: 1.5, communication: 1.3 },
      hardConstraints: [],
    },
    seoTitle: "Copywriter Career Guide (Philippines)",
    seoDescription: "How to become a copywriter, portfolio tips, and typical freelance and full-time salary range.",
  },

  // 14 -----------------------------------------------------------------
  {
    slug: "welder",
    title: "Welder",
    shortDescription: "Joins and fabricates metal parts and structures using welding equipment and techniques.",
    longDescription:
      "Welders fuse and fabricate metal components for construction, manufacturing, and repair work, following blueprints and safety standards. It's a hands-on skilled trade with a fast, TESDA-based entry path, strong local demand, and low oversupply compared to many white-collar careers.",
    industrySlug: "engineering-built-environment",
    categorySlug: "skilled-trades",
    aliases: ["Fabricator", "Welding Technician", "Metal Fabricator"],
    responsibilities: [
      "Read blueprints and specifications to determine welding requirements.",
      "Set up and operate welding equipment safely.",
      "Join, cut, and fabricate metal parts to required specifications.",
      "Inspect completed welds for quality and structural integrity.",
      "Maintain equipment and follow workplace safety protocols.",
    ],
    goodFitIf: [
      "You enjoy hands-on, physical work you can see the results of.",
      "You're comfortable working with tools, heat, and equipment safely.",
      "You'd rather train through a technical program than a college degree.",
      "You like working with your hands more than sitting at a desk.",
    ],
    challengingIf: [
      "You need a fully remote career.",
      "You're uncomfortable with physically demanding or outdoor/site conditions.",
      "Precision, repetitive technical work isn't appealing to you.",
    ],
    workEnvironment: "Workshops, factories, or construction sites; physically demanding, hands-on, on-site work.",
    workStyleSummary: "Hands-on, physically demanding trade work centered on precision and safety.",
    educationLevel: "TESDA_CERTIFICATE",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 3,
    timeToEntryMaxMonths: 9,
    remoteViability: "VERY_LOW",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Welder I",
    midLevelTitle: "Certified Welder",
    seniorLevelTitle: "Welding Supervisor / Inspector",
    relatedCareerSlugs: ["civil-engineer", "logistics-coordinator"],
    skills: [
      { skillSlug: "welding-techniques", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "blueprint-reading", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "equipment-maintenance", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "teamwork", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["field-work", "physically-active", "high-structure", "independent"],
    pathways: [
      {
        type: "TESDA",
        title: "TESDA Welding NC II training",
        description: "A hands-on technical-vocational program covering shielded metal arc welding fundamentals.",
        typicalDurationMonths: 6,
        isRequired: true,
        order: 1,
      },
      {
        type: "APPRENTICESHIP",
        title: "On-the-job apprenticeship",
        description: "Supervised welding experience under a certified welder to build speed and quality.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 2,
      },
      {
        type: "CERTIFICATION",
        title: "Advanced NC III / specialized welding certification",
        description: "Additional certification for higher-paying, specialized welding work.",
        typicalDurationMonths: 4,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "tesda-welding-ncii", isRequired: true, notes: "Standard entry credential for professional welding work." }],
    salaryMin: 15000,
    salaryMax: 24000,
    demand: "HIGH",
    saturation: "LOW",
    quizProfile: {
      idealTraits: {
        hands_on: 90,
        structured: 60,
        independent: 60,
        remote_preference: 10,
        risk_tolerance: 45,
        certification_readiness: 55,
        detail_oriented: 55,
        stability_preference: 55,
      },
      traitWeights: { hands_on: 2, remote_preference: 1.3 },
      hardConstraints: ["remote_only"],
    },
    seoTitle: "Welder Career Guide (Philippines)",
    seoDescription: "TESDA training path, certification, salary range, and daily work of a professional welder.",
  },

  // 15 -----------------------------------------------------------------
  {
    slug: "startup-founder",
    title: "Startup Founder",
    shortDescription: "Builds a new business from an idea, validating, launching, and growing it into a company.",
    longDescription:
      "Startup Founders identify a problem worth solving, build a product or service around it, and grow it into a sustainable business — juggling product, sales, hiring, and fundraising, often with limited resources. It's a high-autonomy, high-uncertainty path with no fixed entry requirements, but real financial and career risk.",
    industrySlug: "entrepreneurship",
    categorySlug: "startup-business-creation",
    aliases: ["Entrepreneur", "Co-Founder", "Business Owner"],
    responsibilities: [
      "Identify and validate a problem worth building a business around.",
      "Build, test, and iterate on a product or service.",
      "Raise funding or manage limited resources to sustain operations.",
      "Hire, lead, and motivate an early team.",
      "Make high-stakes decisions with incomplete information under time pressure.",
    ],
    goodFitIf: [
      "You're comfortable with uncertainty and unpredictable income.",
      "You like taking full ownership and driving decisions yourself.",
      "You can motivate and lead others without a formal management structure.",
      "You're resilient in the face of repeated setbacks.",
    ],
    challengingIf: [
      "You need predictable income and a stable routine.",
      "You'd rather follow an established process than create your own.",
      "High-stakes decisions with incomplete information stress you out.",
    ],
    workEnvironment: "Highly variable — home, co-working spaces, or client sites — with long, irregular hours especially early on.",
    workStyleSummary: "High-autonomy, high-uncertainty work building something from nothing.",
    educationLevel: "VARIES",
    entryDifficulty: "VERY_HARD",
    timeToEntryMinMonths: 0,
    timeToEntryMaxMonths: 24,
    remoteViability: "HIGH",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Founder (Pre-Revenue)",
    midLevelTitle: "Founder / CEO (Early Growth)",
    seniorLevelTitle: "Founder / CEO (Scaling)",
    relatedCareerSlugs: ["e-commerce-manager", "digital-marketing-specialist", "ux-ui-designer"],
    skills: [
      { skillSlug: "business-strategy", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "leadership", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "fundraising-pitching", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "problem-solving", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "negotiation", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "adaptability", proficiency: "ADVANCED", isCore: true },
    ],
    workStyleTagSlugs: ["entrepreneurial", "independent", "remote-friendly", "deadline-driven"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Business fundamentals & lean startup methods",
        description: "Self-directed learning on validation, business models, and early-stage growth.",
        typicalDurationMonths: 3,
        isRequired: true,
        order: 1,
      },
      {
        type: "PORTFOLIO",
        title: "Building and validating an MVP",
        description: "Building a minimum viable product and testing it with real users or customers.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 2,
      },
      {
        type: "BOOTCAMP",
        title: "Startup accelerator or incubator program",
        description: "Structured programs offering mentorship, resources, and sometimes funding.",
        typicalDurationMonths: 4,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [],
    salaryMin: 0,
    salaryMax: 60000,
    demand: "MODERATE",
    saturation: "LOW",
    salaryMethodologyNote:
      "Illustrative POC estimate only — founder income is highly variable and often nonexistent in the early stage; this range does not reflect equity value or outcomes.",
    quizProfile: {
      idealTraits: {
        entrepreneurship: 90,
        risk_tolerance: 85,
        leadership: 80,
        independent: 80,
        analytical: 55,
        communication: 60,
        flexibility_preference: 70,
        creative: 55,
        income_priority: 60,
      },
      traitWeights: { entrepreneurship: 2, risk_tolerance: 1.7, leadership: 1.3 },
      hardConstraints: [],
    },
    seoTitle: "Startup Founder Career Path (Philippines)",
    seoDescription: "What it actually takes to found a startup: skills, risk, income variability, and how to start.",
  },

  // 16 -----------------------------------------------------------------
  {
    slug: "hr-specialist",
    title: "HR Specialist",
    shortDescription: "Supports recruitment, employee relations, and people processes within an organization.",
    longDescription:
      "HR Specialists handle the people side of a business — recruiting, onboarding, employee relations, and policy compliance — acting as a bridge between staff and management. The role rewards strong interpersonal skills and discretion, with paths into specialized HR functions like recruitment, compensation, or learning & development.",
    industrySlug: "business-operations",
    categorySlug: "administrative-support",
    aliases: ["HR Generalist", "People Operations Specialist", "Recruitment Specialist"],
    responsibilities: [
      "Coordinate recruitment, screening, and onboarding of new hires.",
      "Support employee relations, conflict resolution, and disciplinary processes.",
      "Maintain HR records and ensure compliance with labor regulations.",
      "Assist with compensation, benefits, and performance review cycles.",
      "Organize employee engagement and training initiatives.",
    ],
    goodFitIf: [
      "You enjoy supporting and advocating for people at work.",
      "You can hold sensitive information with discretion.",
      "You're comfortable navigating interpersonal conflict calmly.",
      "You like a mix of structured process and people-facing conversations.",
    ],
    challengingIf: [
      "Handling sensitive employee issues would be emotionally draining for you.",
      "You dislike detail-heavy compliance and documentation work.",
      "You'd rather avoid difficult conversations altogether.",
    ],
    workEnvironment: "Office-based or hybrid, with regular one-on-one meetings and cross-department coordination.",
    workStyleSummary: "People-centered administrative work balancing empathy with policy and process.",
    educationLevel: "BACHELORS",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 3,
    timeToEntryMaxMonths: 9,
    remoteViability: "MODERATE",
    freelanceViability: "LOW",
    entryLevelTitle: "HR Assistant",
    midLevelTitle: "HR Specialist / Generalist",
    seniorLevelTitle: "HR Manager / People Operations Lead",
    relatedCareerSlugs: ["customer-service-representative", "k-12-teacher", "virtual-assistant"],
    skills: [
      { skillSlug: "communication", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "negotiation", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "office-administration", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "empathy", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "conflict-resolution", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "excel", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["team-based", "client-facing", "high-structure"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Psychology / HR Management / Business Administration",
        description: "A four-year degree in a people- or business-related field.",
        typicalDurationMonths: 48,
        isRequired: false,
        order: 1,
      },
      {
        type: "CERTIFICATION",
        title: "HR certification program",
        description: "Short professional certification covering recruitment, labor law, and HR practice.",
        typicalDurationMonths: 3,
        isRequired: false,
        order: 2,
      },
      {
        type: "SELF_STUDY",
        title: "On-the-job HR training",
        description: "Many HR specialists build core skills through on-the-job mentorship and training.",
        typicalDurationMonths: 3,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "hr-certification", isRequired: false }],
    salaryMin: 18000,
    salaryMax: 28000,
    demand: "MODERATE",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        people_oriented: 75,
        communication: 75,
        collaborative: 70,
        structured: 60,
        leadership: 45,
        education_readiness: 60,
        stability_preference: 55,
        detail_oriented: 50,
      },
      traitWeights: { people_oriented: 1.4, communication: 1.3 },
      hardConstraints: [],
    },
    seoTitle: "HR Specialist Career Guide (Philippines)",
    seoDescription: "What HR specialists do, entry paths, key skills, and typical salary range.",
  },

  // 17 -----------------------------------------------------------------
  {
    slug: "ux-ui-designer",
    title: "UX/UI Designer",
    shortDescription: "Designs digital product interfaces and experiences that are usable and easy to navigate.",
    longDescription:
      "UX/UI Designers research user needs and design digital product interfaces — apps and websites — that are both usable and visually coherent. The role blends research, problem-solving, and visual craft, and is typically entered through self-study, bootcamps, or a design background backed by a strong case-study portfolio.",
    industrySlug: "creative-media",
    categorySlug: "design",
    aliases: ["UX Designer", "UI Designer", "Product Designer"],
    responsibilities: [
      "Research user needs and pain points through interviews or testing.",
      "Create wireframes, prototypes, and user flows for digital products.",
      "Design visual interfaces consistent with a product's design system.",
      "Test designs with users and iterate based on feedback.",
      "Collaborate closely with developers and product managers.",
    ],
    goodFitIf: [
      "You're curious about how and why people use products the way they do.",
      "You enjoy both problem-solving and visual craft.",
      "You're comfortable presenting and defending design decisions.",
      "You like iterating based on user feedback and data.",
    ],
    challengingIf: [
      "You dislike research and testing phases before getting to visuals.",
      "You'd rather work solo than collaborate closely with engineers and PMs.",
      "Ambiguous problems without a clear right answer frustrate you.",
    ],
    workEnvironment: "Remote or hybrid, computer-based work with regular collaboration with product and engineering teams.",
    workStyleSummary: "Research-informed, iterative design work balancing usability and visual craft.",
    educationLevel: "VARIES",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 4,
    timeToEntryMaxMonths: 10,
    remoteViability: "HIGH",
    freelanceViability: "HIGH",
    entryLevelTitle: "Junior UX/UI Designer",
    midLevelTitle: "UX/UI Designer",
    seniorLevelTitle: "Senior Product Designer / Design Lead",
    relatedCareerSlugs: ["graphic-designer", "software-developer", "digital-marketing-specialist"],
    skills: [
      { skillSlug: "figma", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "ux-research", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "wireframing-prototyping", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "creativity", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "attention-to-detail", proficiency: "INTERMEDIATE", isCore: true },
    ],
    workStyleTagSlugs: ["remote-friendly", "creative-freedom", "deadline-driven", "client-facing"],
    pathways: [
      {
        type: "SELF_STUDY",
        title: "Self-paced UX/UI courses",
        description: "Structured online courses covering research, wireframing, and prototyping tools.",
        typicalDurationMonths: 4,
        isRequired: false,
        order: 1,
      },
      {
        type: "BOOTCAMP",
        title: "UX design bootcamp",
        description: "Intensive, project-based training focused on job-ready UX/UI skills.",
        typicalDurationMonths: 5,
        isRequired: false,
        order: 2,
      },
      {
        type: "PORTFOLIO",
        title: "Case study portfolio",
        description: "A portfolio of 2-4 detailed design case studies is typically required to get hired.",
        typicalDurationMonths: 3,
        isRequired: true,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "ux-certification", isRequired: false }],
    salaryMin: 20000,
    salaryMax: 32000,
    demand: "HIGH",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        creative: 70,
        analytical: 55,
        digital_fluency: 70,
        detail_oriented: 60,
        communication: 55,
        independent: 55,
        flexibility_preference: 55,
        people_oriented: 45,
      },
      traitWeights: { creative: 1.3, digital_fluency: 1.3 },
      hardConstraints: [],
    },
    seoTitle: "UX/UI Designer Career Guide (Philippines)",
    seoDescription: "Entry paths, portfolio expectations, key skills, and salary range for UX/UI designers.",
  },

  // 18 -----------------------------------------------------------------
  {
    slug: "bookkeeper",
    title: "Bookkeeper",
    shortDescription: "Records and organizes day-to-day financial transactions for businesses or clients.",
    longDescription:
      "Bookkeepers maintain accurate, up-to-date financial records — tracking income, expenses, invoices, and reconciliations — that keep a business's books in order for accounting and tax purposes. It's a faster, more accessible entry into finance-adjacent work than accountancy, with strong remote and freelance potential.",
    industrySlug: "finance",
    categorySlug: "accounting",
    aliases: ["Junior Accounting Staff", "Accounts Assistant", "Bookkeeping Associate"],
    responsibilities: [
      "Record daily financial transactions accurately.",
      "Reconcile bank statements and accounts.",
      "Prepare and send invoices, and track payments received.",
      "Organize receipts and supporting documents for tax filing.",
      "Generate basic financial reports for business owners or accountants.",
    ],
    goodFitIf: [
      "You're naturally organized and detail-oriented with numbers.",
      "You like clear, rules-based work with a right answer.",
      "You want a remote-friendly finance-adjacent career without a 5-year degree.",
      "You're comfortable with routine, recurring tasks.",
    ],
    challengingIf: [
      "You find repetitive data-entry work tedious.",
      "You want a highly social, people-facing role.",
      "You dislike double-checking your own work for small errors.",
    ],
    workEnvironment: "Remote, hybrid, or in-office; primarily independent computer-based work with periodic check-ins with clients or accountants.",
    workStyleSummary: "Detail-oriented, independent financial record-keeping work.",
    educationLevel: "ASSOCIATE_OR_DIPLOMA",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 2,
    timeToEntryMaxMonths: 6,
    remoteViability: "HIGH",
    freelanceViability: "HIGH",
    entryLevelTitle: "Junior Bookkeeper",
    midLevelTitle: "Bookkeeper",
    seniorLevelTitle: "Senior Bookkeeper / Accounting Supervisor",
    relatedCareerSlugs: ["accountant", "virtual-assistant", "e-commerce-manager"],
    skills: [
      { skillSlug: "bookkeeping", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "accounting-software", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "excel", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "time-management", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "high-structure", "independent", "deadline-driven"],
    pathways: [
      {
        type: "TESDA",
        title: "TESDA Bookkeeping NC III",
        description: "A technical-vocational program covering core bookkeeping competencies.",
        typicalDurationMonths: 4,
        isRequired: false,
        order: 1,
      },
      {
        type: "SELF_STUDY",
        title: "Bookkeeping fundamentals course",
        description: "Short course or self-study covering double-entry bookkeeping and accounting software.",
        typicalDurationMonths: 2,
        isRequired: true,
        order: 2,
      },
      {
        type: "CERTIFICATION",
        title: "Bookkeeping certification exam",
        description: "Optional certification exam to validate bookkeeping competency.",
        typicalDurationMonths: 1,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "bookkeeping-ncii", isRequired: false }],
    salaryMin: 15000,
    salaryMax: 22000,
    demand: "MODERATE",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        quantitative: 65,
        detail_oriented: 75,
        structured: 65,
        independent: 55,
        digital_fluency: 45,
        stability_preference: 60,
        education_readiness: 45,
        remote_preference: 60,
      },
      traitWeights: { detail_oriented: 1.4, quantitative: 1.2 },
      hardConstraints: [],
    },
    seoTitle: "Bookkeeper Career Guide (Philippines)",
    seoDescription: "How to become a bookkeeper, required skills, remote/freelance potential, and salary range.",
  },

  // 19 -----------------------------------------------------------------
  {
    slug: "logistics-coordinator",
    title: "Logistics Coordinator",
    shortDescription: "Plans and tracks the movement of goods to keep supply chains running smoothly.",
    longDescription:
      "Logistics Coordinators plan shipments, track inventory, and coordinate with suppliers, warehouses, and carriers to keep goods moving efficiently. The role requires strong organization and clear communication across many moving parts, and offers a path into broader supply chain management.",
    industrySlug: "business-operations",
    categorySlug: "customer-operations",
    aliases: ["Supply Chain Coordinator", "Shipping Coordinator", "Operations Coordinator"],
    responsibilities: [
      "Plan and schedule shipments across suppliers and carriers.",
      "Track inventory levels and coordinate replenishment.",
      "Resolve delivery delays, discrepancies, or damaged shipments.",
      "Maintain accurate logistics records and documentation.",
      "Communicate delivery status to internal teams and clients.",
    ],
    goodFitIf: [
      "You're organized and good at tracking many moving parts at once.",
      "You stay calm when a shipment or plan goes wrong and needs fixing fast.",
      "You communicate clearly with suppliers, carriers, and internal teams.",
      "You like process-driven work with measurable outcomes.",
    ],
    challengingIf: [
      "You need a fully remote or flexible-hours role.",
      "Constant problem-solving under time pressure would stress you out.",
      "You dislike coordinating across many external parties.",
    ],
    workEnvironment: "Office or warehouse-adjacent setting, coordinating by phone, email, and logistics software with occasional site visits.",
    workStyleSummary: "Structured, detail-heavy coordination work keeping goods moving on schedule.",
    educationLevel: "BACHELORS",
    entryDifficulty: "MODERATE",
    timeToEntryMinMonths: 2,
    timeToEntryMaxMonths: 6,
    remoteViability: "LOW",
    freelanceViability: "LOW",
    entryLevelTitle: "Logistics Coordinator",
    midLevelTitle: "Senior Logistics Coordinator",
    seniorLevelTitle: "Supply Chain Manager",
    relatedCareerSlugs: ["e-commerce-manager", "civil-engineer", "customer-service-representative"],
    skills: [
      { skillSlug: "logistics-planning", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "inventory-management-systems", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "problem-solving", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "excel", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "negotiation", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["team-based", "high-structure", "deadline-driven", "field-work"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Business Administration / Supply Chain Management",
        description: "A four-year business degree, often with a logistics or operations focus.",
        typicalDurationMonths: 48,
        isRequired: false,
        order: 1,
      },
      {
        type: "SELF_STUDY",
        title: "Logistics & supply chain fundamentals course",
        description: "Short course covering inventory, shipping, and supply chain basics.",
        typicalDurationMonths: 2,
        isRequired: true,
        order: 2,
      },
      {
        type: "CERTIFICATION",
        title: "Supply chain management certification",
        description: "Optional certification to strengthen a logistics career track.",
        typicalDurationMonths: 3,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [],
    salaryMin: 17000,
    salaryMax: 25000,
    demand: "MODERATE",
    saturation: "MODERATE",
    quizProfile: {
      idealTraits: {
        structured: 65,
        detail_oriented: 60,
        communication: 55,
        quantitative: 50,
        stability_preference: 55,
        collaborative: 55,
        independent: 40,
        flexibility_preference: 35,
      },
      traitWeights: { structured: 1.3, detail_oriented: 1.2 },
      hardConstraints: [],
    },
    seoTitle: "Logistics Coordinator Career Guide (Philippines)",
    seoDescription: "What logistics coordinators do, required skills, entry paths, and salary range.",
  },

  // 20 -----------------------------------------------------------------
  {
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    shortDescription: "Monitors, detects, and responds to security threats against an organization's systems.",
    longDescription:
      "Cybersecurity Analysts monitor networks and systems for threats, investigate security incidents, and help harden an organization's defenses against attacks. Demand for this role is rising quickly in the Philippines, and it's entered through IT degrees, vendor certifications, or self-directed home-lab practice.",
    industrySlug: "technology",
    categorySlug: "software-it",
    aliases: ["Security Analyst", "InfoSec Analyst", "SOC Analyst"],
    responsibilities: [
      "Monitor systems and networks for suspicious activity.",
      "Investigate and respond to security incidents.",
      "Perform vulnerability assessments and recommend fixes.",
      "Maintain and configure security tools and firewalls.",
      "Document incidents and contribute to security policy improvements.",
    ],
    goodFitIf: [
      "You enjoy investigating problems methodically, like solving a puzzle.",
      "You're detail-oriented and notice when something looks off.",
      "You like continuously learning about new threats and tools.",
      "You're comfortable with independent, focused technical work.",
    ],
    challengingIf: [
      "You dislike being on-call or responding to urgent incidents.",
      "Constantly evolving threats and tools would frustrate rather than excite you.",
      "You'd rather work with people all day than with systems and logs.",
    ],
    workEnvironment: "Computer-based work, often remote or hybrid, sometimes requiring on-call availability for incident response.",
    workStyleSummary: "Investigative, independent technical work defending systems against threats.",
    educationLevel: "VARIES",
    entryDifficulty: "HARD",
    timeToEntryMinMonths: 6,
    timeToEntryMaxMonths: 18,
    remoteViability: "HIGH",
    freelanceViability: "MODERATE",
    entryLevelTitle: "Junior Security Analyst",
    midLevelTitle: "Cybersecurity Analyst",
    seniorLevelTitle: "Senior Security Analyst / Security Engineer",
    relatedCareerSlugs: ["software-developer", "data-analyst"],
    skills: [
      { skillSlug: "network-security", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "threat-analysis", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "problem-solving", proficiency: "ADVANCED", isCore: true },
      { skillSlug: "attention-to-detail", proficiency: "INTERMEDIATE", isCore: true },
      { skillSlug: "communication", proficiency: "BEGINNER", isCore: false },
      { skillSlug: "python", proficiency: "BEGINNER", isCore: false },
    ],
    workStyleTagSlugs: ["remote-friendly", "high-structure", "independent", "deadline-driven"],
    pathways: [
      {
        type: "DEGREE",
        title: "BS Information Technology / Computer Science",
        description: "A four-year IT or CS degree provides a broad technical foundation.",
        typicalDurationMonths: 48,
        isRequired: false,
        order: 1,
      },
      {
        type: "CERTIFICATION",
        title: "CompTIA Security+ or equivalent",
        description: "An entry-level vendor certification widely recognized in cybersecurity hiring.",
        typicalDurationMonths: 4,
        isRequired: true,
        order: 2,
      },
      {
        type: "SELF_STUDY",
        title: "Home-lab practice & security challenges",
        description: "Hands-on practice through home labs and capture-the-flag style exercises.",
        typicalDurationMonths: 6,
        isRequired: false,
        order: 3,
      },
    ],
    certifications: [{ certificationSlug: "comptia-security-plus", isRequired: false }],
    salaryMin: 25000,
    salaryMax: 40000,
    demand: "VERY_HIGH",
    saturation: "LOW",
    quizProfile: {
      idealTraits: {
        analytical: 80,
        digital_fluency: 85,
        detail_oriented: 70,
        structured: 60,
        independent: 60,
        certification_readiness: 60,
        education_readiness: 55,
        risk_tolerance: 50,
      },
      traitWeights: { digital_fluency: 1.5, analytical: 1.3 },
      hardConstraints: [],
    },
    seoTitle: "Cybersecurity Analyst Career Guide (Philippines)",
    seoDescription: "Entry paths, certifications, in-demand skills, and salary range for cybersecurity analysts.",
  },
];
