// School / Program data for the KnowHow PH POC seed.
// All institutions are fictional / illustrative — invented for demo purposes,
// not real Philippine schools.

import type { CredentialType, DeliveryMode, SchoolType } from "@prisma/client";

export interface SchoolDef {
  slug: string;
  name: string;
  type: SchoolType;
  region: string;
  provinceCity: string;
  description: string;
  accreditationNote: string;
}

export const SCHOOLS: SchoolDef[] = [
  {
    slug: "metro-manila-polytechnic-institute",
    name: "Metro Manila Polytechnic Institute",
    type: "STATE_UNIVERSITY_COLLEGE",
    region: "NCR",
    provinceCity: "Quezon City",
    description: "A fictional state college offering a broad range of technology, business, and engineering degree programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "cebu-coastal-state-college",
    name: "Cebu Coastal State College",
    type: "STATE_UNIVERSITY_COLLEGE",
    region: "Region VII",
    provinceCity: "Cebu City",
    description: "A fictional state college in Cebu offering health sciences and technology programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "northern-luzon-technical-training-center",
    name: "Northern Luzon Technical Training Center",
    type: "TRAINING_PROVIDER",
    region: "Region I",
    provinceCity: "San Fernando, La Union",
    description: "A fictional TESDA-aligned training center focused on technical-vocational programs in trades and bookkeeping, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative TESDA program registration for POC purposes only.",
  },
  {
    slug: "davao-riverside-university",
    name: "Davao Riverside University",
    type: "PRIVATE",
    region: "Region XI",
    provinceCity: "Davao City",
    description: "A fictional private university in Davao offering business, logistics, and entrepreneurship programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "southern-tagalog-institute-of-technology",
    name: "Southern Tagalog Institute of Technology",
    type: "STATE_UNIVERSITY_COLLEGE",
    region: "Region IV-A",
    provinceCity: "Calamba, Laguna",
    description: "A fictional state institute offering accountancy and education degree programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "pampanga-business-and-technology-college",
    name: "Pampanga Business & Technology College",
    type: "PRIVATE",
    region: "Region III",
    provinceCity: "San Fernando, Pampanga",
    description: "A fictional private college offering business, IT, and customer service training programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "knowhow-online-learning-institute",
    name: "KnowHow Online Learning Institute",
    type: "ONLINE_PROVIDER",
    region: "Nationwide (Online)",
    provinceCity: "Online",
    description: "A fictional online-only provider offering short courses, certificates, and bootcamps across tech, marketing, and design fields, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative course registration for POC purposes only.",
  },
  {
    slug: "iloilo-maritime-and-trade-school",
    name: "Iloilo Maritime and Trade School",
    type: "TRAINING_PROVIDER",
    region: "Region VI",
    provinceCity: "Iloilo City",
    description: "A fictional technical-vocational school offering trade certifications including welding, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative TESDA program registration for POC purposes only.",
  },
  {
    slug: "quezon-city-health-sciences-college",
    name: "Quezon City Health Sciences College",
    type: "PRIVATE",
    region: "NCR",
    provinceCity: "Quezon City",
    description: "A fictional private college specializing in nursing and medical technology degree programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "baguio-highlands-college",
    name: "Baguio Highlands College",
    type: "PUBLIC",
    region: "CAR",
    provinceCity: "Baguio City",
    description: "A fictional public college offering teacher education programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "zamboanga-peninsula-polytechnic",
    name: "Zamboanga Peninsula Polytechnic",
    type: "STATE_UNIVERSITY_COLLEGE",
    region: "Region IX",
    provinceCity: "Zamboanga City",
    description: "A fictional state polytechnic offering engineering and technical degree programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
  {
    slug: "national-capital-design-and-arts-academy",
    name: "National Capital Design & Arts Academy",
    type: "PRIVATE",
    region: "NCR",
    provinceCity: "Manila",
    description: "A fictional private academy specializing in multimedia arts and design diploma programs, used here as illustrative demo data.",
    accreditationNote: "Demo institution — illustrative accreditation status for POC purposes only.",
  },
];

export interface ProgramDef {
  slug: string;
  name: string;
  credentialType: CredentialType;
  durationLabel: string;
  deliveryMode: DeliveryMode;
  admissionNotes: string;
  tuitionNote: string;
  schoolSlugs: string[];
  careerSlugs: string[];
}

export const PROGRAMS: ProgramDef[] = [
  {
    slug: "bs-computer-science",
    name: "BS Computer Science",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "HYBRID",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam.",
    tuitionNote: "Illustrative POC estimate: ₱25,000–₱45,000 per semester at a state college; higher at private schools.",
    schoolSlugs: ["metro-manila-polytechnic-institute", "cebu-coastal-state-college"],
    careerSlugs: ["software-developer", "cybersecurity-analyst", "data-analyst"],
  },
  {
    slug: "bs-information-technology",
    name: "BS Information Technology",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "HYBRID",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam.",
    tuitionNote: "Illustrative POC estimate: ₱20,000–₱40,000 per semester.",
    schoolSlugs: ["davao-riverside-university", "pampanga-business-and-technology-college"],
    careerSlugs: ["software-developer", "cybersecurity-analyst", "data-analyst"],
  },
  {
    slug: "bs-accountancy",
    name: "BS Accountancy",
    credentialType: "DEGREE",
    durationLabel: "5 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion with strong math grades, entrance exam.",
    tuitionNote: "Illustrative POC estimate: ₱30,000–₱50,000 per semester.",
    schoolSlugs: ["metro-manila-polytechnic-institute", "southern-tagalog-institute-of-technology"],
    careerSlugs: ["accountant", "bookkeeper"],
  },
  {
    slug: "bs-nursing",
    name: "BS Nursing",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam, health science aptitude.",
    tuitionNote: "Illustrative POC estimate: ₱40,000–₱70,000 per semester, including clinical fees.",
    schoolSlugs: ["quezon-city-health-sciences-college", "cebu-coastal-state-college"],
    careerSlugs: ["nurse"],
  },
  {
    slug: "bs-medical-technology",
    name: "BS Medical Technology",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam, science aptitude.",
    tuitionNote: "Illustrative POC estimate: ₱35,000–₱60,000 per semester, including laboratory fees.",
    schoolSlugs: ["quezon-city-health-sciences-college"],
    careerSlugs: ["medical-technologist"],
  },
  {
    slug: "bs-civil-engineering",
    name: "BS Civil Engineering",
    credentialType: "DEGREE",
    durationLabel: "5 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam, strong math background.",
    tuitionNote: "Illustrative POC estimate: ₱30,000–₱55,000 per semester.",
    schoolSlugs: ["metro-manila-polytechnic-institute", "zamboanga-peninsula-polytechnic"],
    careerSlugs: ["civil-engineer"],
  },
  {
    slug: "bachelor-of-elementary-education",
    name: "Bachelor of Elementary Education",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam.",
    tuitionNote: "Illustrative POC estimate: ₱18,000–₱35,000 per semester.",
    schoolSlugs: ["baguio-highlands-college", "southern-tagalog-institute-of-technology"],
    careerSlugs: ["k-12-teacher"],
  },
  {
    slug: "bs-business-administration",
    name: "BS Business Administration",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "HYBRID",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam.",
    tuitionNote: "Illustrative POC estimate: ₱22,000–₱42,000 per semester.",
    schoolSlugs: ["pampanga-business-and-technology-college", "davao-riverside-university"],
    careerSlugs: ["logistics-coordinator", "hr-specialist", "e-commerce-manager", "startup-founder"],
  },
  {
    slug: "bs-psychology",
    name: "BS Psychology",
    credentialType: "DEGREE",
    durationLabel: "4 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, entrance exam.",
    tuitionNote: "Illustrative POC estimate: ₱25,000–₱45,000 per semester.",
    schoolSlugs: ["metro-manila-polytechnic-institute"],
    careerSlugs: ["hr-specialist"],
  },
  {
    slug: "tesda-welding-nc-ii",
    name: "TESDA Welding NC II",
    credentialType: "TESDA_ALIGNED",
    durationLabel: "3–6 months",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: at least junior high school completion, physical fitness for shop work.",
    tuitionNote: "Illustrative POC estimate: ₱8,000–₱15,000, TESDA scholarship slots often available.",
    schoolSlugs: ["northern-luzon-technical-training-center", "iloilo-maritime-and-trade-school"],
    careerSlugs: ["welder"],
  },
  {
    slug: "tesda-bookkeeping-nc-iii",
    name: "TESDA Bookkeeping NC III",
    credentialType: "TESDA_ALIGNED",
    durationLabel: "3–4 months",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: at least senior high school completion.",
    tuitionNote: "Illustrative POC estimate: ₱5,000–₱10,000, TESDA scholarship slots often available.",
    schoolSlugs: ["northern-luzon-technical-training-center"],
    careerSlugs: ["bookkeeper"],
  },
  {
    slug: "diploma-in-multimedia-arts",
    name: "Diploma in Multimedia Arts",
    credentialType: "DIPLOMA",
    durationLabel: "2–3 years",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, portfolio submission preferred.",
    tuitionNote: "Illustrative POC estimate: ₱25,000–₱45,000 per semester.",
    schoolSlugs: ["national-capital-design-and-arts-academy"],
    careerSlugs: ["graphic-designer", "ux-ui-designer"],
  },
  {
    slug: "ux-ui-design-certificate-program",
    name: "UX/UI Design Certificate Program",
    credentialType: "CERTIFICATE",
    durationLabel: "4–6 months",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: open enrollment, basic computer literacy.",
    tuitionNote: "Illustrative POC estimate: ₱12,000–₱25,000 total.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["ux-ui-designer", "graphic-designer"],
  },
  {
    slug: "full-stack-web-development-bootcamp",
    name: "Full-Stack Web Development Bootcamp",
    credentialType: "BOOTCAMP",
    durationLabel: "4–6 months",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: basic computer literacy, aptitude screening.",
    tuitionNote: "Illustrative POC estimate: ₱30,000–₱60,000 total, some income-share options available.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["software-developer", "cybersecurity-analyst"],
  },
  {
    slug: "data-analytics-short-course",
    name: "Data Analytics Short Course",
    credentialType: "SHORT_COURSE",
    durationLabel: "8–12 weeks",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: open enrollment, basic spreadsheet familiarity.",
    tuitionNote: "Illustrative POC estimate: ₱6,000–₱15,000 total.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["data-analyst", "e-commerce-manager"],
  },
  {
    slug: "digital-marketing-certificate",
    name: "Digital Marketing Certificate",
    credentialType: "CERTIFICATE",
    durationLabel: "3–4 months",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: open enrollment.",
    tuitionNote: "Illustrative POC estimate: ₱8,000–₱18,000 total.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["digital-marketing-specialist", "copywriter", "e-commerce-manager"],
  },
  {
    slug: "virtual-assistant-business-support-short-course",
    name: "Virtual Assistant & Business Support Short Course",
    credentialType: "SHORT_COURSE",
    durationLabel: "6–8 weeks",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: open enrollment, reliable internet connection.",
    tuitionNote: "Illustrative POC estimate: ₱3,000–₱8,000 total.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["virtual-assistant", "customer-service-representative"],
  },
  {
    slug: "customer-experience-call-center-readiness-program",
    name: "Customer Experience & Call Center Readiness Program",
    credentialType: "CERTIFICATE",
    durationLabel: "4–6 weeks",
    deliveryMode: "IN_PERSON",
    admissionNotes: "Illustrative demo admission requirements: senior high school completion, conversational English proficiency.",
    tuitionNote: "Illustrative POC estimate: ₱3,000–₱6,000 total, some employer-sponsored slots available.",
    schoolSlugs: ["pampanga-business-and-technology-college"],
    careerSlugs: ["customer-service-representative", "logistics-coordinator"],
  },
  {
    slug: "supply-chain-and-logistics-management-certificate",
    name: "Supply Chain & Logistics Management Certificate",
    credentialType: "CERTIFICATE",
    durationLabel: "3 months",
    deliveryMode: "HYBRID",
    admissionNotes: "Illustrative demo admission requirements: open enrollment, basic business coursework helpful.",
    tuitionNote: "Illustrative POC estimate: ₱10,000–₱20,000 total.",
    schoolSlugs: ["davao-riverside-university"],
    careerSlugs: ["logistics-coordinator", "e-commerce-manager"],
  },
  {
    slug: "cybersecurity-fundamentals-certificate",
    name: "Cybersecurity Fundamentals Certificate",
    credentialType: "CERTIFICATE",
    durationLabel: "4 months",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: basic IT literacy.",
    tuitionNote: "Illustrative POC estimate: ₱15,000–₱30,000 total.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["cybersecurity-analyst"],
  },
  {
    slug: "copywriting-and-content-strategy-short-course",
    name: "Copywriting & Content Strategy Short Course",
    credentialType: "SHORT_COURSE",
    durationLabel: "6 weeks",
    deliveryMode: "ONLINE",
    admissionNotes: "Illustrative demo admission requirements: open enrollment.",
    tuitionNote: "Illustrative POC estimate: ₱4,000–₱9,000 total.",
    schoolSlugs: ["knowhow-online-learning-institute"],
    careerSlugs: ["copywriter", "digital-marketing-specialist"],
  },
  {
    slug: "entrepreneurship-and-startup-foundations-program",
    name: "Entrepreneurship & Startup Foundations Program",
    credentialType: "CERTIFICATE",
    durationLabel: "3 months",
    deliveryMode: "HYBRID",
    admissionNotes: "Illustrative demo admission requirements: open enrollment, business idea encouraged but not required.",
    tuitionNote: "Illustrative POC estimate: ₱10,000–₱20,000 total, scholarship slots sometimes available.",
    schoolSlugs: ["davao-riverside-university", "knowhow-online-learning-institute"],
    careerSlugs: ["startup-founder", "e-commerce-manager"],
  },
];
